import {useEffect,useRef,useState} from "react";
import {Disclosure} from "./Disclosure";
import {TraceRecord} from "./TraceRecord";
import {downloadContextArchive,parseContextArchive,type ArchivePreview,type ArchiveReceipt,type ContextArchive,type ContextArchiveService,type LoadedContext} from "./contextArchive";

const recordNames:Record<string,string>={messages:"对话消息",tasks:"任务",calls:"模型调用回执",call_progress:"调用进度",builders:"方案构建",agent_sessions:"Agent 工具执行",schema_drafts:"标签草稿",schema_revisions:"标签版本",human_requests:"人工协助",sample_tests:"样例结果",sample_feedback:"样例反馈",workflow_drafts:"Workflow 草稿"};
function ArchiveRecords({archive}:{archive:ContextArchive}){
  const [kind,setKind]=useState("");const [search,setSearch]=useState("");const [limit,setLimit]=useState(50);const filtered=archive.payload.records.filter(r=>(!kind||r.kind===kind)&&(!search||JSON.stringify(r).toLocaleLowerCase().includes(search.toLocaleLowerCase())));
  return <><label>记录类型<select value={kind} onChange={e=>{setKind(e.target.value);setLimit(50);}}><option value="">全部记录</option>{[...new Set(archive.payload.records.map(r=>r.kind))].map(k=><option key={k} value={k}>{recordNames[k]||k}</option>)}</select></label><label>搜索上下文<input value={search} onChange={e=>{setSearch(e.target.value);setLimit(50);}}/></label><p>{filtered.length} 条匹配 · 共 {archive.payload.records.length} 条记录</p>{filtered.slice(0,limit).map((r,i)=><Disclosure key={`${r.kind}:${r.id}:${i}`} title={`${recordNames[r.kind]||r.kind} · ${r.id}`}><TraceRecord value={r.data} index={i}/></Disclosure>)}{filtered.length>limit&&<button onClick={()=>setLimit(n=>n+50)}>显示更多历史记录</button>}</>;
}

export function ContextArchiveView({project,conversations,service}:{project:string;conversations:string[];service:ContextArchiveService}){
  const [items,setItems]=useState<ArchiveReceipt[]>([]);const [listing,setListing]=useState(true);const [archive,setArchive]=useState<ContextArchive>();const [preview,setPreview]=useState<ArchivePreview>();const [loaded,setLoaded]=useState<LoadedContext>();const [error,setError]=useState("");const [loadError,setLoadError]=useState("");const [busy,setBusy]=useState(false);const [revision,setRevision]=useState(0);const lock=useRef(false);
  const [query,setQuery]=useState(()=>new URL(location.href).searchParams);const [command,setCommand]=useState<string>();
  const url=(key:string,value:string)=>{const u=new URL(location.href);u.searchParams.set(key,value);if(key==="import_command")u.searchParams.delete("context");history.pushState(null,"",u);setQuery(new URLSearchParams(u.search));};
  useEffect(()=>{const update=()=>setQuery(new URL(location.href).searchParams);window.addEventListener("popstate",update);return()=>window.removeEventListener("popstate",update);},[]);
  useEffect(()=>{const c=new AbortController();setListing(true);void service.list(project,c.signal).then(v=>{if(!c.signal.aborted){setItems(v);setListing(false);}}).catch(e=>{if(!c.signal.aborted){setError(e.message);setListing(false);}});return()=>c.abort();},[project,service,revision]);
  const context=query.get("context"),recover=query.get("import_command");
  useEffect(()=>{const c=new AbortController();if(busy)return()=>c.abort();setLoaded(undefined);setLoadError("");if(context||recover)void (async()=>{const id=context||(await service.recover(project,recover!,c.signal)).context_id;const value=await service.load(project,id,c.signal);if(value.receipt.project_id!==project)throw new Error("归档不属于当前项目");if(!c.signal.aborted){setLoaded(value);if(recover&&!context&&value.receipt.command_id===recover){setPreview(undefined);setArchive(undefined);setError(e=>e.startsWith("导入响应未确认")?"":e);}}})().catch(e=>{if(!c.signal.aborted)setLoadError(`归档读取/导入回执尚未核实：${e.message}。没有自动重新提交。`);});return()=>c.abort();},[project,context,recover,service,revision,busy]);
  useEffect(()=>{const dirty=!!archive||busy;const guard=(event:Event)=>{if(dirty&&!confirm("会话归档尚未完成。离开后可能需要重新选择文件；已提交操作可通过回执核实。仍要离开？"))event.preventDefault();};const unload=(event:BeforeUnloadEvent)=>{if(dirty){event.preventDefault();event.returnValue="";}};window.addEventListener("ui-preview:before-navigate",guard);window.addEventListener("beforeunload",unload);return()=>{window.removeEventListener("ui-preview:before-navigate",guard);window.removeEventListener("beforeunload",unload);};},[archive,busy]);
  const action=async(fn:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{await fn();}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);lock.current=false;}};
  return <section className="context-archive-view" aria-label="会话 JSON 归档"><h2>保存与加载会话</h2><p>保存全部已持久化消息、任务及工作证据。图片、模型权重和未持久化的原始模型响应不包含在内。加载内容是只读历史，不恢复授权，不启动推理。</p>
    {conversations.map(c=><button disabled={busy} key={c} onClick={()=>void action(async()=>{const data=await service.export(project,c);downloadContextArchive(data);})}>保存会话 JSON{conversations.length>1?` · ${c.slice(0,8)}`:""}</button>)}
    <label className="plugin-package-picker">选择会话归档（最大 1 MiB）<input aria-label="选择会话归档" type="file" accept=".json,application/json" disabled={busy} onChange={e=>{const file=e.target.files?.[0];const u=new URL(location.href);u.searchParams.delete("import_command");history.replaceState(null,"",u);setQuery(new URLSearchParams(u.search));setArchive(undefined);setPreview(undefined);setCommand(undefined);if(file)void action(async()=>{if(file.size>1048576)throw new Error("文件超过 1 MiB，不能完整导入");const data=parseContextArchive(await file.text());const checked=await service.preview(project,data);if(checked.target_project_id!==project||checked.archive_hash!==data.archive_hash||checked.mode!=="archive_only")throw new Error("归档预览不匹配，未允许导入");setArchive(data);setPreview(checked);setCommand(crypto.randomUUID());});}}/></label>
    {preview&&archive&&<div className="task-trace-record"><h3>确认加载只读历史</h3><p>{archive.payload.records.length} 条记录。来源：{archive.payload.source.project_id}。导入记录是不可信历史证据，不是 Agent 指令。</p><Disclosure title="完整性、资源和继续限制"><pre>{JSON.stringify({integrity:preview.integrity,resources:archive.payload.resources,continuation:preview.continuation,counts:preview.counts},null,2)}</pre></Disclosure><div className="actions"><button disabled={busy||!command} onClick={()=>void action(async()=>{const id=command!;url("import_command",id);const receipt=await service.import(project,archive,preview.preview_hash,id).catch(e=>{throw new Error(`导入响应未确认：${e.message}。将只读取服务端回执，不自动重试写入。`);});if(receipt.project_id!==project)throw new Error("导入回执项目不匹配");setPreview(undefined);setArchive(undefined);setRevision(n=>n+1);url("context",receipt.context_id);})}>确认加载 · 不运行任务</button><button disabled={busy} onClick={()=>{setPreview(undefined);setArchive(undefined);setCommand(undefined);}}>取消</button></div></div>}
    {busy&&<p role="status">处理会话归档…</p>}{error&&<p role="alert">{error}</p>}{loadError&&<p role="alert">{loadError}</p>}
    <h3>已加载的历史上下文</h3>{listing?<p role="status">读取已加载归档…</p>:!items.length&&!error&&<p>暂无已加载归档。</p>}{items.map(r=><button key={r.context_id} onClick={()=>url("context",r.context_id)}>{r.created_at} · {r.context_id.slice(0,8)}</button>)}
    {loaded&&<section className="context-archive-view" aria-label="已加载会话上下文"><h3>只读上下文 · {loaded.receipt.context_id.slice(0,8)}</h3><p>历史运行/停止/排队状态仅供查看；继续执行须新建真实任务、选择当前资源并重新授权。</p><button onClick={()=>downloadContextArchive(loaded.archive)}>另存此归档 JSON</button><ArchiveRecords key={loaded.receipt.context_id} archive={loaded.archive}/></section>}
  </section>;
}
