import {useEffect,useRef,useState} from "react";
import type {api} from "../api";
import type {futureProposalApi,FutureProposalPreview,FutureProposalSource,FutureProposalStatus,PendingFutureProposal} from "../conversation-future-proposal-api";
import {futureProposalSourceMatches,parseFutureProposalPending} from "../conversation-future-proposal";
import {projectBudgetAvailability} from "../projectBudget";
import {checkedFutureProposal} from "./SavedFutureProposal";
import {Dialog} from "./Dialog";
type Service={proposal:typeof futureProposalApi;cancel:typeof api.cancelConversationSchema};
type Recovery={pending:PendingFutureProposal;submitted:boolean;stop:boolean};
export function readFutureExecution(raw:string,source:FutureProposalSource):Recovery{
  const value=JSON.parse(raw) as Recovery;if(!value||Object.keys(value).sort().join(",")!=="pending,stop,submitted"||typeof value.submitted!=="boolean"||typeof value.stop!=="boolean")throw new Error("规则建议请求恢复记录无效");
  const pending=parseFutureProposalPending(JSON.stringify(value.pending),source.feedback_call_id,source.scope_answer_command_id);if(!pending||!futureProposalSourceMatches(pending.source,source))throw new Error("规则建议请求不属于当前来源");return {...value,pending};
}
export function FutureProposalControls({service,project,conversation,task,source,storageKey,disabled,onResult,onActive}:{service:Service;project:string;conversation:string;task:string;source:FutureProposalSource;storageKey:string;disabled:boolean;onActive:(active:boolean)=>void;onResult:(v:FutureProposalStatus)=>void}){
  const key=`${storageKey}.proposal-execution`;const [recovery,setRecovery]=useState<Recovery>();const [preview,setPreview]=useState<FutureProposalPreview>();const [approved,setApproved]=useState(false);const [busy,setBusy]=useState(false);const [stopping,setStopping]=useState(false);const [error,setError]=useState("");const [invalid,setInvalid]=useState(false);const [ready,setReady]=useState(false);const [record,setRecord]=useState<FutureProposalStatus|null>();const [generation,setGeneration]=useState(0);const lock=useRef(false);const stopLock=useRef(false);const alive=useRef(true);const identity=JSON.stringify(source);
  const own=(v:FutureProposalStatus)=>checkedFutureProposal(v,task,source);
  const retain=(v:Recovery)=>{localStorage.setItem(key,JSON.stringify(v));setRecovery(v);};
  useEffect(()=>{alive.current=true;try{const raw=localStorage.getItem(key);if(raw)setRecovery(readFutureExecution(raw,source));}catch(e){setInvalid(true);setError((e as Error).message);}setReady(true);return()=>{alive.current=false;};},[key,identity]);
  useEffect(()=>{const c=new AbortController();let timer:ReturnType<typeof setTimeout>;void service.proposal.read(project,conversation,task,source.feedback_call_id,c.signal).then(v=>{if(c.signal.aborted)return;const saved=v?own(v):null;setRecord(saved);if(saved)onResult(saved);if(saved?.receipt?.status==="reserved"||recovery?.submitted&&!saved?.receipt&&!saved?.cancelled)timer=setTimeout(()=>setGeneration(n=>n+1),1800);}).catch(e=>{if(!c.signal.aborted)setError((e as Error).message);});return()=>{c.abort();clearTimeout(timer);};},[service,project,conversation,task,identity,generation,recovery?.submitted]);
  const prepare=async()=>{if(lock.current||disabled||invalid||recovery||record)return;lock.current=true;setBusy(true);setError("");try{const v=await service.proposal.preview(project,conversation,task,source.feedback_call_id,crypto.randomUUID());if(!futureProposalSourceMatches(v.source,source)||v.image_count!==0||v.maximum_calls!==1||!Number.isFinite(Date.parse(v.consent.expires_at)))throw new Error("建议预览范围无效");if(alive.current){setPreview(v);setApproved(false);}}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const execute=async()=>{if(lock.current||disabled||invalid)return;const original=recovery;if(!original&&(!preview||!approved||projectBudgetAvailability(preview.project_call_limit).blocked))return;if(original?.submitted||original?.stop)return;lock.current=true;setBusy(true);setError("");try{const pending=original?.pending||{consent:{...preview!.consent,allow_unknown_cost:true},source:preview!.source,summary:{model_name:preview!.model_name,remote_model:preview!.remote_model,destination:preview!.destination,data_scope:preview!.data_scope,operation:preview!.operation,maximum_output_tokens:preview!.maximum_output_tokens}};const next={pending,submitted:false,stop:false};readFutureExecution(JSON.stringify(next),source);retain(next);setPreview(undefined);let saved=await service.proposal.read(project,conversation,task,source.feedback_call_id);if(!saved)saved=await service.proposal.authorize(project,conversation,task,source.feedback_call_id,pending.consent);saved=own(saved);if(saved.authorization.consent.call_id!==pending.consent.call_id||saved.authorization.consent.scope_hash!==pending.consent.scope_hash)throw new Error("服务器已有不同建议授权，未执行");if(saved.receipt||saved.cancelled){if(alive.current){setRecord(saved);onResult(saved);}return;}const current=readFutureExecution(localStorage.getItem(key)!,source);if(current.stop)throw new Error("已保存停止意图，未发送模型请求");retain({...next,submitted:true});const result=own(await service.proposal.execute(project,conversation,task,source.feedback_call_id,pending.consent.call_id));if(alive.current){setRecord(result);onResult(result);setGeneration(n=>n+1);}}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const stop=async()=>{const original=recovery||(record?{pending:{consent:record.authorization.consent,source:record.authorization.source,summary:record.authorization.summary},submitted:!!record.receipt,stop:false}:undefined);if(stopLock.current||!original)return;stopLock.current=true;setStopping(true);try{retain({...original,stop:true});const receipt=await service.cancel(project,conversation,task,original.pending.consent.call_id);if(receipt.task_id!==task||receipt.call_id!==original.pending.consent.call_id)throw new Error("停止回执归属错误");if(alive.current){setError("停止请求已保存，仍需核实远端结算；不保证费用退回。");setGeneration(n=>n+1);}}catch(e){if(alive.current)setError(`停止结果未知：${(e as Error).message}`);}finally{stopLock.current=false;if(alive.current)setStopping(false);}};
  const active=!!(recovery||record)&&!record?.cancelled&&(!record?.receipt||record.receipt.status==="reserved");
  useEffect(()=>{onActive(active||busy||stopping||!!preview||invalid);},[active,busy,stopping,preview,invalid,onActive]);
  return <section aria-label="生成模型规则建议"><p>单次文本建议；不发送图片，不自动采用、发布或运行方案。</p>{error&&<p role="alert">{error}</p>}{recovery?.submitted&&!record?.receipt&&<p role="status">执行结果待核实，仅查询原请求，不自动重发。</p>}<div className="actions"><button disabled={!ready||disabled||busy||invalid||!!recovery||record!==null} onClick={()=>void prepare()}>查看生成建议的授权范围…</button>{recovery&&!recovery.submitted&&!recovery.stop&&!record?.receipt&&!record?.cancelled&&<button disabled={busy||disabled||invalid} onClick={()=>void execute()}>核实原授权并执行</button>}<button onClick={()=>setGeneration(n=>n+1)}>读取执行状态</button>{active&&<button disabled={stopping} onClick={()=>void stop()}>{stopping?"正在提交停止…":"停止规则建议"}</button>}</div>
    {preview&&<Dialog title="确认模型规则建议范围" onClose={()=>setPreview(undefined)}><p>{preview.model_name} · {preview.remote_model}</p><p>{preview.destination}</p><p>{preview.data_scope} · 图片0张 · 最多1次调用</p><p>累计上限 {preview.cumulative_maximum_calls}；已用 {preview.used_calls}。费用未知。</p><p>到期 {preview.consent.expires_at}</p><label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>同意此范围及未知费用</label>{projectBudgetAvailability(preview.project_call_limit).blocked&&<p role="alert">无法确认可用项目额度，暂不执行。</p>}<div className="actions"><button onClick={()=>setPreview(undefined)}>取消</button><button disabled={!approved||busy||disabled||projectBudgetAvailability(preview.project_call_limit).blocked} onClick={()=>void execute()}>生成规则建议</button></div></Dialog>}
  </section>;
}
