import {useEffect,useRef,useState} from "react";
import {futureSchemaApi,type FutureSchemaState} from "../conversation-future-schema-api";
import {futureSchemaDefinition,futureSchemaDiff,makeFutureSchemaLocal,makeFutureSchemaInput,parseFutureSchemaLocal,futureSchemaSourceMatches,sameSavedFutureSchemaInput,type FutureSchemaLocal,type SchemaFields} from "../conversation-future-schema";
import {Disclosure} from "./Disclosure";
import {SchemaBuilder,type SchemaBuilderService} from "./SchemaBuilder";
export function ownedFutureRules(value:FutureSchemaState,task:string,call:string,scopeCommand:string,digest:string){
  if(value.scope!=="future_tasks_only"||value.base_schema.task_id!==task||value.source.scope_answer_command_id!==scopeCommand||value.source.context_digest!==digest||value.schema&&value.schema.task_id!==task||value.record&&(value.record.input.feedback_call_id!==call||value.record.schema_id!==value.schema?.id))throw new Error("未来规则不属于原反馈范围或任务");return value;
}
export function FutureRules(props:{service:typeof futureSchemaApi;builder:SchemaBuilderService;project:string;conversation:string;task:string;workspace:string;call:string;scopeCommand:string;digest:string}){const [open,setOpen]=useState(false);return <Disclosure title="后续任务规则草稿" onToggle={e=>{if(e.currentTarget.open)setOpen(true);}}>{open&&<Editor key={`${props.workspace}:${props.task}:${props.call}`} {...props}/>}</Disclosure>;}
function Editor({service,builder,project,conversation,task,workspace,call,scopeCommand,digest}:{service:typeof futureSchemaApi;builder:SchemaBuilderService;project:string;conversation:string;task:string;workspace:string;call:string;scopeCommand:string;digest:string}){
  const [builderOpen,setBuilderOpen]=useState(false);const [,setBuilderActive]=useState(false);
  const key=`annotagent.native-future-rules.${workspace}.${project}.${conversation}.${task}.${call}`;const [state,setState]=useState<FutureSchemaState>();const [local,setLocal]=useState<FutureSchemaLocal>();const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [invalid,setInvalid]=useState(false);const lock=useRef(false);const alive=useRef(true);
  const own=(v:FutureSchemaState)=>ownedFutureRules(v,task,call,scopeCommand,digest);
  useEffect(()=>{alive.current=true;const ctrl=new AbortController();void service.read(project,conversation,task,call,ctrl.signal).then(value=>{if(ctrl.signal.aborted)return;const saved=own(value);const raw=localStorage.getItem(key);const restored=raw?parseFutureSchemaLocal(raw,call):undefined;if(raw&&!restored)throw new Error("未来规则恢复记录无效，未覆盖它");if(restored&&!futureSchemaSourceMatches(restored,saved))throw new Error("未来规则来源已变化，未应用本地编辑");if(restored&&saved.record&&(!restored.frozen||!sameSavedFutureSchemaInput(restored.frozen,saved.record.input,call)))throw new Error("服务器保存了不同规则，未覆盖原编辑");setState(saved);setLocal(restored||makeFutureSchemaLocal(call,saved));}).catch(e=>{if(!ctrl.signal.aborted){setInvalid(true);setError((e as Error).message);}});return()=>{alive.current=false;ctrl.abort();};},[service,project,conversation,task,call,scopeCommand,digest,key]);
  const edit=(fields:SchemaFields)=>{if(!local)return;const next={...local,fields};try{localStorage.setItem(key,JSON.stringify(next));setLocal(next);setError("");}catch(e){setInvalid(true);setError((e as Error).message);}};
  const save=async()=>{if(lock.current||!local||!state||invalid)return;lock.current=true;setBusy(true);setError("");try{const latest=own(await service.read(project,conversation,task,call));if(!futureSchemaSourceMatches(local,latest))throw new Error("原规则或反馈范围已改变，未保存");const input=local.frozen||makeFutureSchemaInput(crypto.randomUUID(),latest,local.fields,local.proposal);const next={...local,frozen:input};localStorage.setItem(key,JSON.stringify(next));setLocal(next);const result=latest.record?latest:own(await service.save(project,conversation,task,call,input));if(!result.record||!sameSavedFutureSchemaInput(input,result.record.input,call))throw new Error("规则回执与原请求不匹配");localStorage.removeItem(key);if(alive.current){setState(result);setLocal(makeFutureSchemaLocal(call,result));}}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const after=state?.schema?.definition||(state&&local?futureSchemaDefinition(state.base_schema,local.fields,local.proposal):undefined);const changes=state&&after?futureSchemaDiff(state.base_schema.definition,after):[];
  return <section aria-label="后续任务规则编辑"><p>仅保存新的语义草稿，不修改当前样例、正式标注、Project Schema 或 Published Version；不会自动运行。</p>{error&&<p role="alert">{error}。原请求与输入保留；没有自动重试。</p>}{!state&&!error&&<p role="status">读取原规则…</p>}{state&&local&&<><p role="status">{state.record?"未来规则草稿已保存":busy?"保存中…":local.frozen?"保存结果待核实":"尚未保存到服务器"}</p>{!state.record&&<fieldset disabled={busy||invalid||!!local.frozen}><legend>新规则</legend><label>目标<textarea aria-label="未来规则目标" value={local.fields.goal} onChange={e=>edit({...local.fields,goal:e.target.value})}/></label><label>输出类型<select aria-label="未来规则输出类型" value={local.fields.kind} onChange={e=>edit({...local.fields,kind:e.target.value as SchemaFields["kind"]})}><option value="classification">整图分类</option><option value="bounding_box">框出目标</option></select></label><label>标签<textarea aria-label="未来规则标签" value={local.fields.labels} onChange={e=>edit({...local.fields,labels:e.target.value})}/></label><label>边界规则<textarea aria-label="未来规则边界" value={local.fields.rules} onChange={e=>edit({...local.fields,rules:e.target.value})}/></label></fieldset>}
    <section aria-label="与已测试规则的差异"><h4>规则差异</h4>{!changes.length?<p>没有语义变化。</p>:changes.map(c=><section key={c.field}><h5>{c.field}</h5><p>已测试规则</p><ul>{c.before.map((v,i)=><li key={i}>{v}</li>)}</ul><p>新规则</p><ul>{c.after.map((v,i)=><li key={i}>{v}</li>)}</ul></section>)}</section>
    {!state.record&&<div className="actions"><button disabled={busy||invalid||!!local.frozen} onClick={()=>{localStorage.removeItem(key);setLocal(makeFutureSchemaLocal(call,state));setError("");}}>取消修改</button><button disabled={busy||invalid||!local.fields.goal.trim()||!local.fields.labels.trim()||(!local.frozen&&!changes.length)} onClick={()=>void save()}>{local.frozen?"核实原规则保存":"保存未来规则草稿"}</button></div>}{state.record&&<p>草稿 {state.record.schema_id} · revision {state.schema?.revision}。采用和执行需另行确认。</p>}{state.schema&&state.record&&<>{!builderOpen?<button onClick={()=>setBuilderOpen(true)}>使用此规则构建新方案</button>:<SchemaBuilder service={builder} {...{project,conversation,task}} schema={state.schema} storageKey={key} disabled={busy||invalid} onActive={setBuilderActive}/>}</>}</>}</section>;
}
