import {useEffect,useRef,useState} from "react";
import type {api} from "../api";
import type {FrozenWorkflowVersion,GeometryCalibrationReport,ProjectSummary} from "../types";
import {Disclosure} from "./Disclosure";
export type GeometryCalibrationService=Pick<typeof api,"projectSummary"|"createGeometryCalibration"|"geometryCalibrations">;
type Request=Parameters<typeof api.createGeometryCalibration>[1];
export function calibrationRuns(text:string):string[]{const ids=[...new Set(text.split(/[\s,]+/).filter(Boolean))];if(!ids.length||ids.length>100||ids.some(id=>!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(id)))throw new Error("请输入 1–100 个有效 Run UUID；不会猜测或使用其他运行");return ids;}
export function GeometryCalibration({service,source,workspaceId}:{service:GeometryCalibrationService;source:FrozenWorkflowVersion;workspaceId:string}){
  const [project,setProject]=useState<ProjectSummary>();const [task,setTask]=useState("");const [label,setLabel]=useState("");const [node,setNode]=useState("");const [runs,setRuns]=useState("");const [preview,setPreview]=useState<Request>();const [pending,setPending]=useState(false);const [report,setReport]=useState<GeometryCalibrationReport>();const [error,setError]=useState("");const [busy,setBusy]=useState(false);const lock=useRef(false);
  const key=`annotagent.geometry-calibration.${workspaceId}.${source.project_id}.${source.workflow_id}.${source.version}.${source.content_hash}`;
  useEffect(()=>{let active=true;void service.projectSummary(source.project_id).then(async r=>{if(!active)return;if(r.project.project_id!==source.project_id)throw new Error("项目标签归属不匹配");setProject(r.project);const raw=localStorage.getItem(key);if(raw){setPending(true);const saved=JSON.parse(raw);if(saved.hash!==source.content_hash||saved.request.workflow_id!==source.workflow_id||saved.request.workflow_version!==source.version)throw new Error("本地校准请求与当前冻结版本不匹配");setPreview(saved.request);if(saved.report){const records=await service.geometryCalibrations(source.project_id);if(!active)return;const actual=records.calibrations.find(c=>c.report.id===saved.report.id)?.report;if(!actual||actual.key.task_id!==saved.request.task_id||actual.key.label_id!==saved.request.label_id)throw new Error("服务器未找到匹配的原校准回执");setReport(actual);}}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[service,source,key]);
  useEffect(()=>{const dirty=!!task||!!node||!!runs||!!preview;const guard=(e:Event)=>{if(!pending&&dirty&&!confirm("校准范围尚未提交，离开会丢失本次输入。仍要离开？"))e.preventDefault();};const unload=(e:BeforeUnloadEvent)=>{if(!pending&&dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("ui-preview:before-navigate",guard);window.addEventListener("beforeunload",unload);return()=>{window.removeEventListener("ui-preview:before-navigate",guard);window.removeEventListener("beforeunload",unload);};},[task,node,runs,preview,pending]);
  const selected=project?.annotation_schema.find(t=>t.id===task);
  const prepare=()=>{try{if(!selected||selected.kind!=="bounding_box"||!source.draft.nodes.some(n=>n.id===node&&n.model_binding))throw new Error("请选择已有框标签组和绑定模型的真实节点");setPreview({workflow_id:source.workflow_id,workflow_version:source.version,node_id:node,task_id:task,label_id:label||undefined,evidence_run_ids:calibrationRuns(runs)});setError("");}catch(e){setError((e as Error).message);}};
  const create=async()=>{if(lock.current||pending||!preview)return;lock.current=true;setBusy(true);setError("");try{localStorage.setItem(key,JSON.stringify({hash:source.content_hash,request:preview}));setPending(true);const result=await service.createGeometryCalibration(source.project_id,preview);if(result.calibration.key.task_id!==preview.task_id||result.calibration.key.label_id!==preview.label_id)throw new Error("校准回执与所选标签范围不匹配");setReport(result.calibration);localStorage.setItem(key,JSON.stringify({hash:source.content_hash,request:preview,report:result.calibration}));}catch(e){setError((e as Error).message);}finally{lock.current=false;setBusy(false);}};
  return <section aria-label="创建几何校准"><p>仅计算已有人工审核/修正证据，不重新推理、不调用模型、不修改发布版本。仅支持框标注。服务器会核对证据 Run 的精确版本及模型范围；证据不足会如实记录。</p>{error&&<p role="alert">{error}</p>}{!project&&!error&&<p role="status">读取标签范围…</p>}
    {project&&!pending&&!preview&&<><label>框标签组<select aria-label="校准标签组" value={task} onChange={e=>{setTask(e.target.value);setLabel("");}}><option value="">选择标签组</option>{project.annotation_schema.filter(t=>t.kind==="bounding_box").map(t=><option key={t.id} value={t.id}>{t.display_name}</option>)}</select></label><label>类别<select aria-label="校准类别" value={label} onChange={e=>setLabel(e.target.value)}><option value="">全部类别</option>{selected?.labels.map(l=><option key={l}>{l}</option>)}</select></label><label>冻结模型节点<select aria-label="校准模型节点" value={node} onChange={e=>setNode(e.target.value)}><option value="">选择节点</option>{source.draft.nodes.filter(n=>n.model_binding).map(n=><option key={n.id} value={n.id}>{n.id} · {n.model_binding}</option>)}</select></label><label>证据 Run ID<textarea aria-label="校准证据 Run" value={runs} onChange={e=>setRuns(e.target.value)}/></label><p>从当前项目运行详情复制 ID，以逗号或换行分隔；不自动列入旧历史。</p><button onClick={prepare}>检查校准范围</button></>}
    {preview&&<><Disclosure title="精确校准请求" open><pre>{JSON.stringify(preview,null,2)}</pre></Disclosure>{!pending&&<div className="actions"><button disabled={busy} onClick={()=>setPreview(undefined)}>返回修改</button><button disabled={busy} onClick={()=>void create()}>确认计算校准</button></div>}</>}
    {pending&&!report&&<p role="status">{busy?"正在计算校准…":"校准请求已发出，结果待核实。此接口没有幂等命令，不能直接重发；请刷新上方校准证据核对实际记录。"}</p>}
    {report&&<p role="status">校准记录已保存：{report.status} · {report.sample_count} 个样本 · {report.id}。保存记录不代表校准通过。</p>}
  </section>;
}
