import {useEffect,useRef,useState} from "react";
import type {api} from "../api";
import type {GlobalModelDefaults as Defaults,RegistryModelProfile} from "../types";
import {Disclosure} from "./Disclosure";
export type GlobalDefaultsService=Pick<typeof api,"agentModelBindings"|"saveAgentModelBindings"|"compatibleModelProfiles">;
const roles=["pipeline_builder","vision_language","text_generation"] as const;
const titles={pipeline_builder:"Pipeline Builder 默认模型",vision_language:"视觉语言默认模型",text_generation:"文字生成默认模型"};
export function GlobalModelDefaults({service}:{service:GlobalDefaultsService}) {
  const [base,setBase]=useState<Defaults>();const [draft,setDraft]=useState<Defaults>({});const [choices,setChoices]=useState<Record<string,RegistryModelProfile[]>>({});const [error,setError]=useState("");const [message,setMessage]=useState("");const [busy,setBusy]=useState(false);const [reload,setReload]=useState(0);const live=useRef(0);const pending=useRef(false);
  const dirty=!!base&&JSON.stringify(base)!==JSON.stringify(draft);
  useEffect(()=>{const generation=++live.current;setBase(undefined);setError("");void Promise.all([service.agentModelBindings(),service.compatibleModelProfiles({input_modalities:["text"],capabilities:["text_generation"],tool_calls:true,structured_output:true}),service.compatibleModelProfiles({input_modalities:["image"],capabilities:["vision_language"]}),service.compatibleModelProfiles({input_modalities:["text"],capabilities:["text_generation"]})]).then(([value,builder,vision,text])=>{if(generation!==live.current)return;setBase(value);setDraft(value);setChoices({pipeline_builder:builder.models,vision_language:vision.models,text_generation:text.models});}).catch(e=>{if(generation===live.current)setError(e.message);});return()=>{live.current++;};},[service,reload]);
  useEffect(()=>{const guard=(e:Event)=>{if((dirty||busy)&&!window.confirm("全局默认模型有未保存修改或操作结果待核实，仍离开？"))e.preventDefault();};const unload=(e:BeforeUnloadEvent)=>{if(dirty||busy){e.preventDefault();e.returnValue="";}};window.addEventListener("ui-preview:before-navigate",guard);window.addEventListener("beforeunload",unload);return()=>{window.removeEventListener("ui-preview:before-navigate",guard);window.removeEventListener("beforeunload",unload);};},[dirty,busy]);
  const save=async()=>{if(!base||!dirty||pending.current)return;pending.current=true;setBusy(true);setError("");setMessage("");const generation=live.current;try{const current=await service.agentModelBindings();if(JSON.stringify(current)!==JSON.stringify(base))throw new Error("服务器默认配置已变化；请重新读取后编辑");const saved=await service.saveAgentModelBindings(draft);if(generation===live.current){setBase(saved);setDraft(saved);setMessage("全局默认已保存；没有启动模型，也没有修改已发布 Workflow。");}}catch(e){if(generation===live.current)setError(`${(e as Error).message}。编辑保留，未自动重试。`);}finally{pending.current=false;if(generation===live.current)setBusy(false);}};
  return <Disclosure title="全局默认模型"><section aria-label="全局默认模型配置"><p>用于后续未明确选择模型的请求。不同于当前任务的模型偏好，不改在途请求或已发布 Workflow 中的绑定；保存不发起收费探测。</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}
    {!base&&!error&&<p role="status">读取默认配置和兼容 Registry 模型…</p>}{base&&<form onSubmit={e=>{e.preventDefault();void save();}}>{roles.map(role=><label key={role}>{titles[role]}<select disabled={busy} value={draft[role]||""} onChange={e=>setDraft(value=>({...value,[role]:e.target.value||undefined}))}><option value="">无全局默认</option>{draft[role]&&!choices[role]?.some(m=>m.id===draft[role])&&<option value={draft[role]}>当前绑定（不在兼容清单）：{draft[role]}</option>}{choices[role]?.map(model=><option key={model.id} value={model.id}>{model.display_name} · {model.remote_model_id}</option>)}</select></label>)}<div className="actions"><button type="button" disabled={busy||!dirty} onClick={()=>{setDraft(base);setError("");}}>取消默认模型修改</button><button disabled={busy||!dirty}>保存全局默认</button></div></form>}
    <button disabled={busy} onClick={()=>{if(!dirty||window.confirm("丢弃未保存的默认模型修改并重新读取？"))setReload(v=>v+1);}}>重新读取默认模型</button>
  </section></Disclosure>;
}
