import {expect,it} from "vitest";
import {assertVisualSelection,deliverySampleResultFromCanonical,formalVisualSelectionFromCanonical,selectedMessage,taskIsComplete,type CanonicalVisualSelectionItem,type MainlineTaskView,type SampleVisualSelection} from "./mainline";
const selection:SampleVisualSelection={project_id:"p",conversation_id:"c",task_id:"t",project_schema_revision:"schema",image:{image_id:"image",sha256:"pixels"},sample:{draft_id:"draft",draft_revision:2,sample_test_id:"sample"},candidate:{candidate_id:"candidate",source_artifact_id:"artifact"},annotation:{kind:"bounding_box",label:"ball"},result_revision:"sample:feedback:3"};
it("freezes a complete candidate reference for the existing feedback protocol",()=>{const input=selectedMessage("message","这个框太大",selection);selection.candidate.candidate_id="changed";expect(input.image).toEqual({image_id:"image",sha256:"pixels"});expect(input.reference).toMatchObject({scope:"sample_candidate",candidate_id:"candidate",source_artifact_id:"artifact",draft_revision:2});});
it("rejects partial and cross-task references before send",()=>{expect(()=>assertVisualSelection({...selection,task_id:"other"},"p","t")).toThrow("没有发送反馈");expect(()=>assertVisualSelection({...selection,image:{...selection.image,sha256:""}},"p","t")).toThrow("没有发送反馈");});
it("freezes a server-issued formal annotation reference without deriving lineage in the browser",()=>{
  const reference={scope:"formal_annotation" as const,task_id:"t",project_schema_revision:"schema",intent_revision:3,intent_sha256:"intent",processing_operation_id:"operation",batch_id:"batch",source_run_id:"run",annotation_id:"annotation",annotation_revision_id:"annotation-revision",expected_snapshot_sha256:"snapshot"};
  const formal=formalVisualSelectionFromCanonical({project_id:"p",conversation_id:"c",task_id:"t",image_id:"image",image_sha256:"pixels",annotation:{annotation_id:"annotation",label:"ball",value:{kind:"bounding_box",rect:[.1,.2,.3,.4]},annotation_revision_id:"annotation-revision",feedback_available:true,conversation_reference:reference}});
  const input=selectedMessage("message","边界仍然太宽",formal);
  formal.reference.annotation_id="changed";
  expect(input).toMatchObject({image:{image_id:"image",sha256:"pixels"},reference:{scope:"formal_annotation",annotation_id:"annotation",annotation_revision_id:"annotation-revision",expected_snapshot_sha256:"snapshot"}});
  expect(()=>formalVisualSelectionFromCanonical({project_id:"p",conversation_id:"c",task_id:"t",image_id:"image",image_sha256:"pixels",annotation:{annotation_id:"other",label:"ball",value:{kind:"bounding_box",rect:[.1,.2,.3,.4]},annotation_revision_id:"annotation-revision",feedback_available:true,conversation_reference:reference}})).toThrow("当前会话引用");
});
it("defines task completion as a reconciled Ready training package",()=>{const base={completion:{task_completed:false,package_ready:false},package:{jobs:[]}} as unknown as MainlineTaskView;expect(taskIsComplete(base)).toBe(false);const ready={...base,completion:{...base.completion,task_completed:true,package_ready:true},package:{...base.package,jobs:[{phase:"ready"}]}} as MainlineTaskView;expect(taskIsComplete(ready)).toBe(true);expect(taskIsComplete({...ready,package:{...ready.package,jobs:[]}})).toBe(false);});
it("joins geometry to canonical candidate identity by id and rejects duplicates",()=>{
  const annotation={id:"candidate",image_id:"image",task_id:"sample",label:"ball",value:{kind:"bounding_box" as const,rect:[0.1,0.2,0.3,0.4] as [number,number,number,number]},attributes:{},source:"sample",review_status:"needs_review" as const,provenance:{},created_at:""};
  const item={project_id:"p",conversation_id:"c",task_id:"t",project_schema_revision:"schema",draft_id:"d",draft_revision:2,sample_test_id:"s",sample_status:"passed",operation_status:"succeeded",result_available:true,images:[{image_id:"image",image_sha256:"pixels",result_revision:"result",candidates:[{candidate_id:"candidate",annotation_kind:"bounding_box",label:"ball",source_artifact_id:"artifact",feedback_available:true},{candidate_id:"no-artifact",annotation_kind:"bounding_box",label:"ball",source_artifact_id:null,feedback_available:false}]}]} satisfies CanonicalVisualSelectionItem;
  expect(deliverySampleResultFromCanonical(item,{image:[annotation]})).toMatchObject({images:[{source_artifacts:{candidate:"artifact"},annotations:[{id:"candidate"}]}]});
  const duplicate=structuredClone(item);duplicate.images[0].candidates.push({...duplicate.images[0].candidates[0]});
  expect(()=>deliverySampleResultFromCanonical(duplicate,{image:[annotation]})).toThrow("duplicated");
});
