import { useEffect, useState } from "react";
import type { RegistryModelProfile } from "../types";
import type { api } from "../api";
import { Dialog } from "./Dialog";
export type ModelProfileService = Pick<typeof api, "modelProfiles" | "updateModelProfile">;
export function ModelProfiles({service}:{service:ModelProfileService}) {
  const [models,setModels]=useState<RegistryModelProfile[]>();
  const [edit,setEdit]=useState<RegistryModelProfile>();
  const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
  const reload=async()=>setModels((await service.modelProfiles()).models);
  useEffect(()=>{let live=true; void service.modelProfiles().then(r=>{if(live)setModels(r.models);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[service]);
  useEffect(()=>{const guard=(e:Event)=>{if(edit&&!window.confirm("放弃尚未保存的模型修改？"))e.preventDefault();};const unload=(e:BeforeUnloadEvent)=>{if(edit){e.preventDefault();e.returnValue="";}};window.addEventListener("ui-preview:before-navigate",guard);window.addEventListener("beforeunload",unload);return()=>{window.removeEventListener("ui-preview:before-navigate",guard);window.removeEventListener("beforeunload",unload);};},[edit]);
  return <section aria-label="模型配置"><h2>模型配置</h2><p>修改 Registry 配置，不自动探测或调用模型，也不改写已有发布版本。</p>{error&&<p role="alert" className="error">{error}</p>}{!models&&!error&&<p role="status">读取模型配置…</p>}<button onClick={()=>void reload().catch(e=>setError(e.message))}>重新读取</button>{models?.map(m=><div className="settings-row" key={m.id}><div><strong>{m.display_name}</strong><p>{m.remote_model_id} · {m.status}</p><p>{m.task_capabilities.join(" · ")}</p></div><button disabled={m.locked} onClick={()=>{setError("");setEdit(structuredClone(m));}}>{m.locked?"已锁定":"编辑配置"}</button></div>)}{edit&&<Dialog title="编辑模型配置" onClose={()=>{if(!busy&&window.confirm("放弃编辑？"))setEdit(undefined);}}><form onSubmit={e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");void service.modelProfiles().then(async r=>{const current=r.models.find(m=>m.id===edit.id);if(!current||current.revision!==edit.revision)throw new Error("模型版本已变化，请取消并重新读取后编辑");await service.updateModelProfile(edit.id,{revision:edit.revision,display_name:edit.display_name,remote_model_id:edit.remote_model_id,enabled:edit.enabled});setEdit(undefined);await reload();}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}><label>显示名称<input required value={edit.display_name} onChange={e=>setEdit({...edit,display_name:e.target.value})}/></label><label>远程模型 ID<input required value={edit.remote_model_id} onChange={e=>setEdit({...edit,remote_model_id:e.target.value})}/></label><label><input type="checkbox" checked={edit.enabled} onChange={e=>setEdit({...edit,enabled:e.target.checked})}/>启用模型</label>{error&&<p role="alert">{error}</p>}<div className="actions"><button type="button" disabled={busy} onClick={()=>setEdit(undefined)}>取消</button><button disabled={busy}>{busy?"保存中…":"保存配置"}</button></div></form></Dialog>}</section>;
}
