import {useEffect,useRef,useState} from "react";
import type {api} from "../api";
import type {NodeReplayCommand,NodeReplayPreview,NodeReplayReceipt} from "../types";
import {Dialog} from "./Dialog";
import {Disclosure} from "./Disclosure";
export type NodeReplayService=Pick<typeof api,"nodeReplayPreview"|"nodeReplayCommand"|"nodeReplayReceipt">;
export function replayScopeAllowed(p:NodeReplayPreview,project:string,run:string,node:string){
  if(p.project_id!==project||p.source_run_id!==run||p.node_id!==node||!p.scope_hash)throw new Error("Replay 预览归属不匹配");
  return p.available&&p.refusal_reasons.length===0&&p.limits.maximum_model_requests===0&&!p.limits.unknown_cost&&p.destinations.sandbox&&!p.destinations.formal_annotations&&!p.destinations.source_checkpoint_write&&!p.destinations.published_write;
}
export function assertReplayReceipt(r:NodeReplayReceipt,c:NodeReplayCommand,run:string,node:string){
  if(r.project_id!==c.project_id||r.command_id!==c.command_id||r.run_id!==run||r.node_id!==node||r.request.command_id!==c.command_id||r.request.project_id!==c.project_id||r.request.scope_hash!==c.scope_hash||r.request.maximum_model_requests!==c.maximum_model_requests||r.request.allow_unknown_cost!==c.allow_unknown_cost||!["running","completed","outcome_unknown"].includes(r.status))throw new Error("Replay 回执与原命令不匹配");
  if(r.result&&(r.result.source_run_id!==run||r.result.replayed_from!==node||!r.result.sandbox||r.result.inspection.project_id!==c.project_id))throw new Error("Replay 结果来源不匹配");return r;
}
export function NodeReplay({projectId,runId,nodeId,workspaceId,service}:{projectId:string;runId:string;nodeId:string;workspaceId:string;service:NodeReplayService}){
  const key=`annotagent.node-replay.${workspaceId}.${projectId}.${runId}.${nodeId}`;
  const [preview,setPreview]=useState<NodeReplayPreview>();const [command,setCommand]=useState<NodeReplayCommand>();const [receipt,setReceipt]=useState<NodeReplayReceipt>();const [error,setError]=useState("");const [blocked,setBlocked]=useState(false);const [busy,setBusy]=useState(false);const [confirm,setConfirm]=useState(false);const [readVersion,setReadVersion]=useState(0);const lock=useRef(false);const alive=useRef(false);
  useEffect(()=>{alive.current=true;try{const raw=localStorage.getItem(key);if(raw){const c=JSON.parse(raw) as NodeReplayCommand;if(c.project_id!==projectId||!c.scope_hash||typeof c.command_id!=="string"||!/^[0-9a-f-]{36}$/i.test(c.command_id)||c.maximum_model_requests!==0||c.allow_unknown_cost!==false)throw new Error("Replay 恢复记录无效，没有执行任何请求");setCommand(c);}}catch(e){setError((e as Error).message);setBlocked(true);}return()=>{alive.current=false;};},[key,projectId]);
  useEffect(()=>{if(!command)return;const ctrl=new AbortController();let timer:ReturnType<typeof setTimeout>;const read=async()=>{try{const r=assertReplayReceipt(await service.nodeReplayReceipt(projectId,runId,nodeId,command.command_id,ctrl.signal),command,runId,nodeId);if(ctrl.signal.aborted)return;setReceipt(r);setError("");if(r.status==="running")timer=setTimeout(()=>void read(),1000);}catch(e){if(!ctrl.signal.aborted)setError(`${(e as Error).message} 原命令保留；未重新执行。`);}};void read();return()=>{ctrl.abort();clearTimeout(timer);};},[service,projectId,runId,nodeId,command,readVersion]);
  const inspect=async()=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{const p=await service.nodeReplayPreview(projectId,runId,nodeId);replayScopeAllowed(p,projectId,runId,nodeId);if(alive.current)setPreview(p);}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const send=async(c:NodeReplayCommand)=>{if(lock.current)return;lock.current=true;setBusy(true);setError("");try{localStorage.setItem(key,JSON.stringify(c));setCommand(c);setConfirm(false);const r=assertReplayReceipt(await service.nodeReplayCommand(runId,nodeId,c),c,runId,nodeId);if(alive.current){setReceipt(r);setReadVersion(v=>v+1);}}catch(e){if(alive.current)setError(`${(e as Error).message} 结果未确认；刷新或读取回执不会重发。`);}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const allowed=preview&&replayScopeAllowed(preview,projectId,runId,nodeId);
  return <section aria-label="节点 Replay"><h3>节点重放</h3><p>从保存的 checkpoint 重放到下游 sandbox，不改原运行、正式标注或 Published Version。当前仅支持服务器允许的 Core／离线 Mock 范围，真实模型绑定尚未接通。</p>{error&&<p role="alert">{error}</p>}
    {!command&&<button disabled={busy||blocked} onClick={()=>void inspect()}>检查重放范围</button>}
    {preview&&!command&&<><p>来源节点：{preview.node_id} · 执行超时 {preview.limits.timeout_seconds} 秒 · 外部模型调用上限 {preview.limits.maximum_model_requests}</p><p>下游范围（实际分支以结果为准）：{preview.downstream_nodes.map(n=>n.node_id).join(" → ")}</p><p>保留上游：{preview.preserved_upstream_nodes.join("、")||"无"}</p>{!allowed&&<p role="status">当前不可执行：{preview.refusal_reasons.join("；")||"此范围超出当前 UI 支持的授权协议"}</p>}<Disclosure title="完整服务器预览"><pre>{JSON.stringify(preview,null,2)}</pre></Disclosure><button disabled={busy||!allowed||blocked} onClick={()=>setConfirm(true)}>确认重放范围…</button></>}
    {command&&<><p role="status">{receipt?.status==="running"?"Sandbox 正在执行；离开页面不会取消":receipt?.status==="completed"?"已保存重放报告；不代表所有节点成功或标注被接受":receipt?.status==="outcome_unknown"?"执行结果未知；不会自动重试或恢复":"原命令结果待核实"}</p><button disabled={busy} onClick={()=>setReadVersion(v=>v+1)}>读取原命令回执</button>{!receipt&&<button disabled={busy||blocked} onClick={()=>void send(command)}>核实原重放请求</button>}{receipt?.failure&&<p>{receipt.failure}</p>}{receipt?.result&&<><p>实际执行：{receipt.result.reexecuted_nodes.join("、")}</p><p>实际保留：{receipt.result.preserved_upstream_nodes.join("、")}</p>{receipt.result.inspection.nodes.map(n=><Disclosure key={n.node_id} title={`${n.node_id} · ${n.status}`}><p>{n.latency_ms} ms · {n.error?.summary||"无节点错误记录"}</p><pre>{JSON.stringify({inputs:n.inputs,outputs:n.outputs},null,2)}</pre></Disclosure>)}</>}</>}
    {confirm&&preview&&<Dialog title="确认 Sandbox 节点重放" onClose={()=>setConfirm(false)}><p>{nodeId} 及其下游范围；最多 {preview.limits.maximum_model_requests} 次外部模型调用。未授权付费或外传，不写正式标注。</p><p>这是一次新 sandbox 执行，不是仅查看历史结果。</p><div className="actions"><button onClick={()=>setConfirm(false)}>取消</button><button disabled={busy||!allowed} onClick={()=>void send({project_id:projectId,command_id:crypto.randomUUID(),scope_hash:preview.scope_hash,maximum_model_requests:0,allow_unknown_cost:false})}>开始 Sandbox 重放</button></div></Dialog>}
  </section>;
}
