import { useEffect, useState } from "react";
import type { api } from "../api";
export type RuntimeSettingsService = Pick<typeof api,"settings"|"saveSettings">;
type Fields = Record<string, string | number>;
function fields(value: unknown): Fields { return value && typeof value === "object" ? Object.fromEntries(Object.entries(value).filter(([,v])=>typeof v==="number"||typeof v==="string")) : {}; }
export function RuntimeSettings({service}:{service:RuntimeSettingsService}) {
  const [base,setBase]=useState<{pricing:Fields;budget:Fields}>(); const [draft,setDraft]=useState<typeof base>(); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [saved,setSaved]=useState(false);
  const dirty=JSON.stringify(base)!==JSON.stringify(draft);
  useEffect(()=>{let current=true;void service.settings().then(r=>{if(current){const value={pricing:fields(r.pricing),budget:fields(r.budget)};setBase(value);setDraft(value);}}).catch(e=>{if(current)setError(e.message);});return()=>{current=false;};},[service]);
  useEffect(()=>{const guard=(e:Event)=>{if(dirty&&!window.confirm("放弃未保存的运行配置？"))e.preventDefault();};const unload=(e:BeforeUnloadEvent)=>{if(dirty){e.preventDefault();e.returnValue="";}};window.addEventListener("ui-preview:before-navigate",guard);window.addEventListener("beforeunload",unload);return()=>{window.removeEventListener("ui-preview:before-navigate",guard);window.removeEventListener("beforeunload",unload);};},[dirty]);
  return <section aria-label="服务器运行配置"><h2>价格与运行预算</h2><p>这是原存储设置页已有的运行配置，不是磁盘容量统计。修改不会重置任务授权或已消耗预算。</p>{error&&<p role="alert" className="error">{error}</p>}{!draft&&!error&&<p role="status">读取服务器配置…</p>}{draft&&<form onSubmit={e=>{e.preventDefault();if(busy)return;setBusy(true);setError("");setSaved(false);void service.settings().then(async current=>{if(JSON.stringify({pricing:fields(current.pricing),budget:fields(current.budget)})!==JSON.stringify(base))throw new Error("服务器配置已变化，请刷新后重新编辑");const result=await service.saveSettings({...current,pricing:{...fields(current.pricing),...draft.pricing},budget:{...fields(current.budget),...draft.budget}});const value={pricing:fields(result.pricing),budget:fields(result.budget)};setBase(value);setDraft(value);setSaved(true);}).catch(e=>setError(e.message)).finally(()=>setBusy(false));}}>{(["pricing","budget"] as const).map(group=><fieldset key={group}><legend>{group==="pricing"?"价格配置":"后续运行预算"}</legend>{Object.entries(draft[group]).map(([key,value])=><label key={key}>{key}<input required type={typeof value==="number"?"number":"text"} step="any" value={value} onChange={e=>{setSaved(false);setDraft({...draft,[group]:{...draft[group],[key]:typeof base?.[group][key]==="number"?Number(e.target.value):e.target.value}});}}/></label>)}</fieldset>)}<div className="actions"><button type="button" disabled={busy||!dirty} onClick={()=>{setDraft(base);setError("");}}>取消</button><button disabled={busy||!dirty}>{busy?"保存中…":"保存运行配置"}</button><span role="status">{saved?"已保存到服务器":dirty?"有未保存修改":"已读取配置"}</span></div></form>}</section>;
}
