import {useEffect,useRef,useState} from "react";
import type {api} from "../api";
import type {ConversationBuilderItem,ConversationBuilderPreview} from "../types";
import {builderConsent,restoreBuilderPending} from "../conversation-builder-pending";
import {builderMatchesSchema} from "../conversation-schema-history";
import {projectBudgetAvailability} from "../projectBudget";
import {Dialog} from "./Dialog";
import {Disclosure} from "./Disclosure";
export type SchemaBuilderService=Pick<typeof api,"conversationBuilderPreview"|"conversationBuilderHistory"|"launchConversationBuilder"|"cancelConversationSchema"|"conversationSchemaCancellations">;
export function matchesSchemaBuild(item:ConversationBuilderItem,task:string,schema:{id:string;revision:number}){return item.operation.task_id===task&&builderMatchesSchema(item,schema)&&!item.operation.evidence?.repair_source&&item.session?.working_draft?.build_mode.kind!=="repair_draft";}
export function schemaBuildOutcome(item:ConversationBuilderItem){
  const outcome=item.session?.outcome||item.operation.evidence?.outcome;
  const draft=item.operation.evidence?.draft_id||item.session?.working_draft?.draft_id;
  if(outcome==="failed"||item.session?.phase==="failed")return "构建失败";
  if(item.operation.status==="completed"&&draft&&outcome==="draft_ready_for_human_review")return "草稿已生成，待人工检查";
  return item.operation.status==="completed"?"回执已结算，未确认生成草稿":item.operation.status;
}
export function SchemaBuilder({project,conversation,task,schema,storageKey,disabled,service,onActive}:{project:string;conversation:string;task:string;schema:{id:string;revision:number};storageKey:string;disabled:boolean;service:SchemaBuilderService;onActive:(active:boolean)=>void}){
  const key=`${storageKey}.builder.${schema.revision}`;
  const [stopIntent,setStopIntent]=useState<string>();
  const [cancelledIds,setCancelledIds]=useState<string[]>([]);
  const stopLock=useRef(false);const [stopping,setStopping]=useState(false);
  const [entries,setEntries]=useState<ConversationBuilderItem[]>([]);const [preview,setPreview]=useState<ConversationBuilderPreview>();const [pending,setPending]=useState<NonNullable<ReturnType<typeof restoreBuilderPending>>>();const [error,setError]=useState("");const [invalid,setInvalid]=useState(false);const [busy,setBusy]=useState(false);const [ready,setReady]=useState(false);const [approved,setApproved]=useState(false);const [generation,setGeneration]=useState(0);const [stopMessage,setStopMessage]=useState("");const alive=useRef(true);const lock=useRef(false);
useEffect(()=>{alive.current=true;try{const raw=localStorage.getItem(key);if(raw){const saved=restoreBuilderPending(raw,schema);if(!saved)throw new Error("Builder 恢复记录无效，未自动执行");setPending(saved);}const stop=localStorage.getItem(`${key}.stop`);if(stop){if(!/^[0-9a-f-]{36}$/i.test(stop))throw new Error("停止请求恢复记录无效");setStopIntent(stop);setStopMessage("停止结果待核实；不会重新提交模型请求。");}}catch(e){setInvalid(true);setError((e as Error).message);}setReady(true);return()=>{alive.current=false;};},[key]);
  useEffect(()=>{if(!ready)return;const c=new AbortController();let timer:ReturnType<typeof setTimeout>|undefined;
    const read=async()=>{try{const [history,cancellations]=await Promise.all([service.conversationBuilderHistory(project,conversation,task,c.signal,pending?{operation_id:pending.consent.selection.operation_id}:undefined),service.conversationSchemaCancellations(project,conversation,task,c.signal)]);if(c.signal.aborted)return;if(cancellations.some(v=>v.task_id!==task))throw new Error("取消回执任务归属不匹配");setCancelledIds(cancellations.map(v=>v.call_id));
const found=history.items.filter(item=>matchesSchemaBuild(item,task,schema));if(pending&&history.items.some(item=>item.operation.id!==pending.consent.selection.operation_id||!matchesSchemaBuild(item,task,schema)))throw new Error("Builder 回执范围不匹配");setEntries(found);if(found.length)setError("");
      if(pending&&found.some(item=>item.operation.status!=="reserved")){localStorage.removeItem(key);setPending(undefined);}
      const target=stopIntent||pending?.consent.selection.operation_id||found.find(item=>item.operation.status==="reserved")?.operation.id||found.find(item=>cancellations.some(v=>v.call_id===item.operation.id))?.operation.id;
      if(target&&cancellations.some(v=>v.call_id===target)){setStopMessage("取消请求已保存；是否已结算以实际构建记录为准，在途费用可能仍未知。");if(found.some(item=>item.operation.id===target&&item.operation.status!=="reserved")){localStorage.removeItem(`${key}.stop`);setStopIntent(undefined);}}
      if(found.some(item=>item.operation.status==="reserved")||pending)timer=setTimeout(()=>void read(),1500);
    }catch(e){if(!c.signal.aborted)setError((e as Error).message);}};void read();return()=>{c.abort();if(timer)clearTimeout(timer);};
  },[ready,project,conversation,task,schema.id,schema.revision,service,pending,generation,key,stopIntent]);
  const running=entries.some(e=>e.operation.status==="reserved");
  useEffect(()=>{onActive(busy||!!pending||running||!!preview||invalid||!!stopIntent);return()=>onActive(false);},[busy,pending,running,preview,invalid,onActive,stopIntent]);
const prepare=async()=>{if(lock.current||disabled||pending||running||invalid||stopIntent)return;lock.current=true;setBusy(true);setError("");try{const p=await service.conversationBuilderPreview(project,conversation,task,{operation_id:crypto.randomUUID(),schema_id:schema.id,schema_revision:schema.revision});if(!restoreBuilderPending(JSON.stringify({preview:p,consent:builderConsent(p)}),schema))throw new Error("Builder 预览与当前草稿不匹配");if(alive.current){setApproved(false);setPreview(p);}}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const launch=async()=>{if(lock.current||disabled||invalid||stopIntent||(pending&&cancelledIds.includes(pending.consent.selection.operation_id))||(!pending&&(!preview||!approved||projectBudgetAvailability(preview.project_call_limit).blocked)))return;
    const envelope=pending||(preview?{preview,consent:builderConsent(preview)}:undefined);if(!envelope)return;lock.current=true;setBusy(true);setError("");
    try{const cancelled=await service.conversationSchemaCancellations(project,conversation,task);if(!alive.current)return;if(cancelled.some(v=>v.task_id!==task))throw new Error("取消回执归属不匹配");if(cancelled.some(v=>v.call_id===envelope.consent.selection.operation_id))throw new Error("此构建已有取消请求，未重新提交");localStorage.setItem(key,JSON.stringify(envelope));setPending(envelope);setPreview(undefined);const operation=await service.launchConversationBuilder(project,conversation,task,envelope.consent);if(operation.id!==envelope.consent.selection.operation_id||operation.task_id!==task)throw new Error("Builder 返回了其他操作");if(alive.current)setGeneration(v=>v+1);}catch(e){if(alive.current)setError(`${(e as Error).message}。请先核实服务器回执，不创建替代请求。`);}finally{lock.current=false;if(alive.current)setBusy(false);}
  };
  const stop=async(id:string)=>{if(stopLock.current)return;stopLock.current=true;setStopping(true);try{localStorage.setItem(`${key}.stop`,id);setStopIntent(id);setStopMessage("正在请求停止；尚未确认远端结果。");const receipt=await service.cancelConversationSchema(project,conversation,task,id);if(receipt.call_id!==id||receipt.task_id!==task)throw new Error("停止回执归属不匹配");if(alive.current){setStopMessage("取消请求已保存；等待服务器结算，在途费用可能仍未知。");setGeneration(v=>v+1);}}catch(e){if(alive.current){setError((e as Error).message);setStopMessage("停止结果未知；请读取构建记录，不重新提交模型请求。");}}finally{stopLock.current=false;if(alive.current)setStopping(false);}};
  return <section aria-label="从语义草稿构建方案"><p>使用此 Schema revision {schema.revision} 生成方案草稿；不测试图片、不发布、不接受标注。</p>
    {error&&<p role="alert">{error}</p>}{stopMessage&&<p role="status">{stopMessage}</p>}
    <div className="actions"><button disabled={!ready||disabled||busy||!!pending||running||invalid||!!stopIntent} onClick={()=>void prepare()}>检查此草稿的构建授权…</button><button disabled={busy} onClick={()=>setGeneration(v=>v+1)}>读取构建记录</button>{pending&&!running&&<button disabled={disabled||busy||invalid||!!stopIntent||cancelledIds.includes(pending.consent.selection.operation_id)} onClick={()=>void launch()}>核实同一构建请求</button>}{(pending||running)&&<button disabled={stopping} onClick={()=>void stop(pending?.consent.selection.operation_id||entries.find(e=>e.operation.status==="reserved")!.operation.id)}>停止此构建</button>}</div>
{entries.map(item=><Disclosure key={item.operation.id} title={`构建记录 · ${item.operation.status} · ${schemaBuildOutcome(item)}`}><p>{item.session?.phase||item.operation.status}</p><p>{item.session?.next_action||item.operation.evidence?.error}</p>{item.session?.unresolved_bindings?.map((v,i)=><p key={i}>{v}</p>)}{(item.operation.evidence?.draft_id||item.session?.working_draft?.draft_id)&&<a href={`/projects/${encodeURIComponent(project)}/manage/pipelines/${encodeURIComponent(item.operation.evidence?.draft_id||item.session!.working_draft!.draft_id)}`}>查看实际方案草稿</a>}</Disclosure>)}
    {preview&&<Dialog title="确认语义草稿构建范围" onClose={()=>{if(!busy)setPreview(undefined);}}><p>{preview.model_name} · {preview.remote_model}</p><p>数据目的地：{preview.destination}</p><p>{preview.data_scope} · 图片 {preview.image_count} 张</p><p>最多 {preview.maximum_builder_calls} 次 Builder 调用；累计上限 {preview.maximum_calls}，已用 {preview.used_calls}。费用未知。</p><p>授权到期：{preview.expires_at}</p><p>{preview.operation}</p>{projectBudgetAvailability(preview.project_call_limit).blocked&&<p role="alert">项目调用额度不足或未能核实，请先管理额度。</p>}<label><input type="checkbox" checked={approved} onChange={e=>setApproved(e.target.checked)}/>同意此范围及未知费用，仅构建草稿</label><div className="actions"><button disabled={busy} onClick={()=>setPreview(undefined)}>取消</button><button disabled={!approved||disabled||busy||projectBudgetAvailability(preview.project_call_limit).blocked} onClick={()=>void launch()}>生成方案草稿</button></div></Dialog>}
  </section>;
}
