import {useEffect,useRef,useState} from "react";
import {api} from "../api";
import {feedbackApi,type FeedbackStatus,type FeedbackScopeChoice,type ScopeAnswerInput} from "../conversation-feedback-api";
import {candidateFeedbackKind,makeFeedbackScopeChoice,parseLocalScopeAnswer,sameScopeAnswerInput,scopeAnswerConflicts,type LocalScopeAnswer} from "../conversation-feedback-scope";
import {Disclosure} from "./Disclosure";
import {FutureRules} from "./FutureRules";
import {futureSchemaApi} from "../conversation-future-schema-api";
export const taskFeedbackService={history:api.conversationHistory,feedback:feedbackApi,futureRules:futureSchemaApi,builder:api};
export type TaskFeedbackService=typeof taskFeedbackService;
export function ownedFeedback(value:FeedbackStatus,conversation:string,task:string,message:string){
  if(value.authorization.context.message.conversation_id!==conversation||value.authorization.grant.task_id!==task||value.authorization.consent.message_id!==message||value.authorization.context.message.input.id!==message)throw new Error("反馈记录不属于当前任务和消息");return value;
}
export function TaskFeedback(props:{service:TaskFeedbackService;project:string;conversation:string;task:string;workspace:string}){const [open,setOpen]=useState(false);return <Disclosure title="反馈记录与修改范围" onToggle={e=>{if(e.currentTarget.open)setOpen(true);}}>{open&&<FeedbackPage key={`${props.workspace}:${props.project}:${props.task}`} {...props}/>}</Disclosure>;}
function FeedbackPage({service,project,conversation,task,workspace}:{service:TaskFeedbackService;project:string;conversation:string;task:string;workspace:string}){
  const [before,setBefore]=useState<number>();const [rows,setRows]=useState<FeedbackStatus[]>([]);const [next,setNext]=useState<number>();const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{const c=new AbortController();setBusy(true);setError("");void (async()=>{const messages=await service.history(project,conversation,before,c.signal);if(messages.some(m=>m.conversation_id!==conversation))throw new Error("消息历史归属不匹配");const source=messages.filter(m=>m.input.reference?.scope==="sample_candidate"&&m.input.reference.task_id===task);const values=await Promise.all(source.map(async m=>{const v=await service.feedback.forMessage(project,conversation,task,m.input.id,c.signal);return v?ownedFeedback(v,conversation,task,m.input.id):null;}));const minimum=messages.length?Math.min(...messages.map(m=>m.sequence)):undefined;if(before!==undefined&&minimum!==undefined&&minimum>=before)throw new Error("反馈历史分页未前进");if(!c.signal.aborted){setRows(values.filter((v):v is FeedbackStatus=>!!v));setNext(messages.length===100?minimum:undefined);}})().catch(e=>{if(!c.signal.aborted)setError((e as Error).message);}).finally(()=>{if(!c.signal.aborted)setBusy(false);});return()=>c.abort();},[service,project,conversation,task,before]);
  return <section aria-label="任务反馈记录"><p>只读取已保存的反馈。范围选择记录你的意图，不直接修改标注、不调用模型或执行方案。</p>{busy?<p role="status">读取反馈…</p>:error?<p role="alert">{error}</p>:<>{rows.length===0&&<p>当前历史页没有此任务的已授权反馈。</p>}{rows.map(value=><FeedbackScope key={value.authorization.consent.call_id} {...{service,project,conversation,task,workspace,value}}/>)}</>}<div className="actions"><button disabled={busy||before===undefined} onClick={()=>setBefore(undefined)}>最新历史</button><button disabled={busy||next===undefined} onClick={()=>setBefore(next)}>较早历史</button></div></section>;
}
function FeedbackScope({service,project,conversation,task,workspace,value}:{service:TaskFeedbackService;project:string;conversation:string;task:string;workspace:string;value:FeedbackStatus}){
  const [current,setCurrent]=useState(value);const call=value.authorization.consent.call_id;const key=`annotagent.native-feedback-scope.${workspace}.${project}.${conversation}.${task}.${call}`;
  const [local,setLocal]=useState<LocalScopeAnswer>({call_id:call,context_digest:value.scope_context_digest});const [error,setError]=useState("");const [invalid,setInvalid]=useState(false);const [busy,setBusy]=useState(false);const lock=useRef(false);const alive=useRef(true);
  useEffect(()=>{alive.current=true;try{const raw=localStorage.getItem(key);if(raw){const parsed=parseLocalScopeAnswer(raw,call);if(!parsed)throw new Error("反馈范围恢复记录无效");setLocal(parsed);}}catch(e){setInvalid(true);setError((e as Error).message);}return()=>{alive.current=false;};},[key]);
  useEffect(()=>{if(current.scope_answer&&scopeAnswerConflicts(local,current.scope_answer))setError("服务器已保存不同范围；浏览器原选择未覆盖服务器记录");},[current.scope_answer,local]);
  const retain=(next:LocalScopeAnswer)=>{try{localStorage.setItem(key,JSON.stringify(next));setLocal(next);setError("");}catch(e){setInvalid(true);setError((e as Error).message);}};
  const save=async()=>{if(lock.current||invalid)return;const choice=makeFeedbackScopeChoice(local.scope,local.reason,candidateFeedbackKind(current.authorization.context.candidate));if(!choice)return;lock.current=true;setBusy(true);setError("");try{const latest=ownedFeedback(await service.feedback.status(project,conversation,task,call),conversation,task,value.authorization.consent.message_id);if(latest.authorization.consent.call_id!==call||latest.scope_context_digest!==local.context_digest||latest.cancelled)throw new Error("反馈范围已变化或已取消，未提交");const input:ScopeAnswerInput=local.frozen||{command_id:crypto.randomUUID(),expected_context_digest:local.context_digest,choice};localStorage.setItem(key,JSON.stringify({...local,frozen:input}));setLocal({...local,frozen:input});const saved=latest.scope_answer||await service.feedback.answerScope(project,conversation,task,call,input);if(saved.call_id!==call||saved.task_id!==task||saved.conversation_id!==conversation||!sameScopeAnswerInput(saved.input,input))throw new Error("服务器保存了不同的范围，未覆盖原选择");localStorage.removeItem(key);if(alive.current)setCurrent({...latest,scope_answer:saved});}catch(e){if(alive.current)setError((e as Error).message);}finally{lock.current=false;if(alive.current)setBusy(false);}};
  const labels:Record<FeedbackScopeChoice["scope"],string>={current_candidate:"仅这个对象",current_image_class:"当前图片中的这一类",project_future_rule:"后续任务的标签规则"};const decision=current.decision&&"Ok"in current.decision?current.decision.Ok:null;const kind=candidateFeedbackKind(current.authorization.context.candidate);const frozen=busy||invalid||!!local.frozen||!!current.scope_answer||current.cancelled;
  return <Disclosure title={current.authorization.context.message.input.text}><p>{decision?.question||current.error||"此反馈尚未产生有效决策"}</p><p role="status">{current.cancelled?"已取消":current.scope_answer?`已保存范围：${labels[current.scope_answer.input.choice.scope]}`:current.receipt?.status||"授权已保存，尚未执行"}</p>{decision?.decision==="clarify_scope"&&!current.scope_answer&&!current.cancelled&&<><fieldset disabled={frozen}><legend>你希望修改哪里？</legend>{Object.entries(labels).map(([scope,label])=><label key={scope}><input type="radio" name={key} checked={local.scope===scope} onChange={()=>retain({...local,scope:scope as FeedbackScopeChoice["scope"],reason:undefined})}/>{label}</label>)}{local.scope==="current_candidate"&&<label>原因<select aria-label="反馈原因" value={local.reason||""} onChange={e=>retain({...local,reason:e.target.value as LocalScopeAnswer["reason"]})}><option value="">选择原因</option>{kind==="bounding_box"&&<option value="poor_boundary">边界不合适</option>}<option value="wrong_label">标签不对</option><option value="wrong_target">目标找错</option></select></label>}</fieldset><button disabled={busy||invalid||!makeFeedbackScopeChoice(local.scope,local.reason,kind)} onClick={()=>void save()}>{local.frozen?"核实原范围选择":"保存反馈范围"}</button></>}{current.scope_answer&&<p>仅保存修改范围；现有标注与未来规则尚未改变。</p>}{current.scope_answer?.input.choice.scope==="project_future_rule"&&!current.cancelled&&<FutureRules builder={service.builder} service={service.futureRules} {...{project,conversation,task,workspace,call}} scopeCommand={current.scope_answer.input.command_id} digest={current.scope_context_digest}/>}{error&&<p role="alert">{error}。原选择保留，未自动重试。</p>}</Disclosure>;
}
