use std::{
    collections::{BTreeMap, BTreeSet},
    path::{Path, PathBuf},
};

use annotagent_core::{
    ArtifactKind, ArtifactRef, ArtifactValidationState, BoxPrompt, BoxPromptSetArtifact, Detection,
    DetectionScore, DetectionSetArtifact, DetectionSource, ImageId, LabelId, ModelCapability,
    NormalizedRect, PipelineArtifact, VisionCapability,
};
use annotagent_model_bundle::{
    CommercialUseStatus, ExpectedOutputSummary, ModelBundleFile, ModelBundleId,
    ModelBundleManifest, ModelBundleSmokeRequest, ModelContractDocument, ModelContractReference,
    ModelExportMetadata, ModelFileRole, ModelFileTensorContract, ModelFormat, ModelLicenseMetadata,
    ModelRuntimeMetadata, ModelSourceMetadata, ModelTensorConnection, ModelTensorContract,
    ModelTestSuiteReference, OutputTolerances, PluginCompatibilityRequirement,
    RedistributionStatus, Sha256Digest, pack_model_bundle, verify_model_bundle,
};
use annotagent_plugin_api::PluginManifest;
use chrono::{DateTime, Utc};
use prost::Message;
use semver::Version;
use url::Url;

use crate::{
    ModelCatalog, ModelCatalogEntry, ModelCatalogError, ModelLicenseSummary, PlatformRequirement,
    PublisherIdentity,
};

pub const BUILTIN_FIXTURE_CATALOG_ID: &str = "org.annotagent.catalog.fixture";
pub const PROMPTED_SEGMENTATION_FIXTURE_BUNDLE_ID: &str =
    "org.annotagent.models.fixture-prompted-segmentation";
const FIXTURE_BUNDLE_VERSION: &str = "1.0.0";
const FIXTURE_MODEL_ID: &str = "sam-vit-b-onnx";
const FIXTURE_PLUGIN_MANIFEST: &str =
    include_str!("../../../plugins/sam-onnx/annotagent-plugin.toml");
const FIXTURE_LICENSE: &str = "MIT License\n\nCopyright (c) 2026 AnnotAgent contributors\n\nPermission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the \"Software\"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n";
const FIXTURE_SOURCE_NOTICE: &str = "AnnotAgent-generated deterministic ONNX contract fixture. This is not SAM, does not contain upstream model weights, and provides no accuracy evidence.\n";
const FIXTURE_PNG: &[u8] = &[
    0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a, 0x00, 0x00, 0x00, 0x0d, 0x49, 0x48, 0x44, 0x52,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x08, 0x04, 0x00, 0x00, 0x00, 0xb5, 0x1c, 0x0c,
    0x02, 0x00, 0x00, 0x00, 0x0b, 0x49, 0x44, 0x41, 0x54, 0x78, 0xda, 0x63, 0x64, 0xf8, 0x0f, 0x00,
    0x01, 0x05, 0x01, 0x01, 0x27, 0x18, 0xe3, 0x66, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45, 0x4e, 0x44,
    0xae, 0x42, 0x60, 0x82,
];

pub struct BuiltinFixtureCatalog {
    pub catalog: ModelCatalog,
    pub package_path: PathBuf,
}

/// Materializes the deterministic offline Fixture as a normal `.annotmodel` package. The ONNX
/// graphs are generated by Rust and executed by the real Plugin/ORT path, but are deliberately
/// non-publishable and make no model-quality claim.
pub fn build_builtin_fixture_catalog(
    data_root: &Path,
) -> Result<BuiltinFixtureCatalog, ModelCatalogError> {
    let plugin = PluginManifest::from_toml(FIXTURE_PLUGIN_MANIFEST).map_err(|error| {
        provisioning(format!("invalid built-in fixture Plugin contract: {error}"))
    })?;
    let model = plugin
        .models
        .iter()
        .find(|model| model.id == FIXTURE_MODEL_ID)
        .ok_or_else(|| provisioning("fixture Plugin model is missing".to_owned()))?;
    let bundle_id = ModelBundleId::parse(PROMPTED_SEGMENTATION_FIXTURE_BUNDLE_ID)
        .map_err(|error| provisioning(error.to_string()))?;
    let bundle_version =
        Version::parse(FIXTURE_BUNDLE_VERSION).map_err(|error| provisioning(error.to_string()))?;
    let expected_contract = Sha256Digest::of_bytes(
        &serde_json::to_vec(model).map_err(|error| provisioning(error.to_string()))?,
    );
    let package_path = builtin_catalog_bundle_path(
        data_root,
        BUILTIN_FIXTURE_CATALOG_ID,
        &bundle_id,
        &bundle_version,
    );
    let current = package_path.is_file()
        && verify_model_bundle(&package_path).is_ok_and(|verified| {
            verified.manifest.id == bundle_id
                && verified.manifest.version == bundle_version
                && verified.manifest.fixture
                && !verified.manifest.publishable
                && verified
                    .manifest
                    .compatible_plugins
                    .iter()
                    .any(|requirement| {
                        requirement.plugin_id == plugin.id
                            && requirement.model_id == model.id
                            && requirement.contract_hash == expected_contract
                    })
        });
    if !current {
        write_fixture_package(&package_path, &plugin)?;
    }
    let verified = verify_model_bundle(&package_path)
        .map_err(|error| provisioning(format!("built-in fixture verification failed: {error}")))?;
    if verified.manifest.id != bundle_id
        || verified.manifest.version != bundle_version
        || !verified.manifest.fixture
        || verified.manifest.publishable
    {
        return Err(provisioning(
            "built-in fixture package identity or publication policy is invalid".to_owned(),
        ));
    }
    let size = std::fs::metadata(&package_path)?.len();
    let platform_requirements = plugin
        .compatibility
        .targets
        .iter()
        .map(|target| PlatformRequirement {
            target: target.clone(),
            execution_providers: BTreeSet::from(["cpu".to_owned()]),
            minimum_memory_mb: plugin.resources.minimum_memory_mb,
            minimum_disk_bytes: size,
        })
        .collect();
    let catalog = ModelCatalog {
        schema_version: crate::MODEL_CATALOG_SCHEMA_VERSION.to_owned(),
        catalog_id: BUILTIN_FIXTURE_CATALOG_ID.to_owned(),
        generated_at: DateTime::parse_from_rfc3339("2026-09-01T00:00:00Z")
            .expect("fixed fixture date is valid")
            .with_timezone(&Utc),
        entries: vec![ModelCatalogEntry {
            bundle_id,
            bundle_version,
            display_name: verified.manifest.display_name.clone(),
            description: verified
                .manifest
                .description
                .clone()
                .unwrap_or_else(|| "Offline prompted-segmentation Fixture".to_owned()),
            capabilities: BTreeSet::from([ModelCapability::PromptedSegmentation]),
            compatible_plugins: verified.manifest.compatible_plugins.clone(),
            platform_requirements,
            // A stable logical identity is retained in exported Catalog JSON. Built-in fixture
            // installs resolve to the content-addressed local package and never fetch this URL.
            bundle_url: Url::parse(&format!(
                "https://models.annotagent.dev/builtin-fixtures/{PROMPTED_SEGMENTATION_FIXTURE_BUNDLE_ID}/{FIXTURE_BUNDLE_VERSION}.annotmodel"
            ))
            .expect("built-in fixture URL is valid"),
            bundle_sha256: verified.bundle_digest,
            bundle_size_bytes: size,
            license_summary: ModelLicenseSummary {
                name: verified.manifest.license.name.clone(),
                license_url: verified.manifest.license.license_url.clone(),
                license_digest: verified.manifest.license.license_digest.clone(),
                redistribution: verified.manifest.license.redistribution,
                commercial_use: verified.manifest.license.commercial_use,
                requires_acceptance: false,
            },
            publisher: PublisherIdentity {
                id: "org.annotagent".to_owned(),
                display_name: "AnnotAgent".to_owned(),
                verified: true,
            },
            fixture: true,
            publishable: false,
        }],
        signature: None,
    };
    catalog.validate()?;
    // Keep this read so a Plugin contract change cannot silently leave a stale compatible entry.
    if catalog.entries[0].compatible_plugins[0].contract_hash != expected_contract {
        return Err(provisioning(
            "built-in fixture catalog has a stale Plugin contract hash".to_owned(),
        ));
    }
    Ok(BuiltinFixtureCatalog {
        catalog,
        package_path,
    })
}

#[must_use]
pub fn builtin_catalog_bundle_path(
    data_root: &Path,
    catalog_id: &str,
    bundle_id: &ModelBundleId,
    version: &Version,
) -> PathBuf {
    data_root
        .join("catalog-bundles")
        .join(catalog_id)
        .join(format!("{bundle_id}@{version}.annotmodel"))
}

fn write_fixture_package(
    package_path: &Path,
    plugin: &PluginManifest,
) -> Result<(), ModelCatalogError> {
    let staging = package_path.with_extension(format!("source-{}", uuid::Uuid::new_v4()));
    let result = (|| {
        for directory in ["files", "contracts", "licenses", "tests"] {
            std::fs::create_dir_all(staging.join(directory))?;
        }
        let encoder = fixture_encoder_model().encode_to_vec();
        let decoder = fixture_decoder_model().encode_to_vec();
        std::fs::write(staging.join("files/sam_image_encoder.onnx"), &encoder)?;
        std::fs::write(staging.join("files/sam_mask_decoder.onnx"), &decoder)?;
        std::fs::write(staging.join("licenses/MODEL-LICENSE"), FIXTURE_LICENSE)?;
        std::fs::write(
            staging.join("licenses/SOURCE-NOTICE"),
            FIXTURE_SOURCE_NOTICE,
        )?;
        std::fs::write(staging.join("tests/input-image.png"), FIXTURE_PNG)?;

        let contract = fixture_contract()?;
        let contract_bytes = serde_json::to_vec_pretty(&contract)?;
        std::fs::write(
            staging.join("contracts/sam-compatible-v1.json"),
            &contract_bytes,
        )?;
        let smoke = fixture_smoke_request()?;
        std::fs::write(
            staging.join("tests/request.json"),
            serde_json::to_vec_pretty(&smoke)?,
        )?;
        let expected = ExpectedOutputSummary {
            required_artifact_kinds: BTreeSet::from([ArtifactKind::MaskSet]),
            minimum_artifact_count: 1,
            minimum_item_count: 1,
            require_non_empty_mask: true,
        };
        std::fs::write(
            staging.join("tests/expected-summary.json"),
            serde_json::to_vec_pretty(&expected)?,
        )?;
        let tolerances = OutputTolerances {
            maximum_duration_ms: 120_000,
            minimum_mask_coverage: Some(1.0),
            maximum_mask_coverage: Some(1.0),
        };
        std::fs::write(
            staging.join("tests/tolerances.json"),
            serde_json::to_vec_pretty(&tolerances)?,
        )?;

        let model = plugin
            .models
            .iter()
            .find(|model| model.id == FIXTURE_MODEL_ID)
            .ok_or_else(|| provisioning("fixture Plugin model is missing".to_owned()))?;
        let encoder_role = ModelFileRole::parse("image_encoder")
            .map_err(|error| provisioning(error.to_string()))?;
        let decoder_role = ModelFileRole::parse("mask_decoder")
            .map_err(|error| provisioning(error.to_string()))?;
        let roles = BTreeSet::from([encoder_role.clone(), decoder_role.clone()]);
        let manifest = ModelBundleManifest {
            schema_version: annotagent_model_bundle::MODEL_BUNDLE_MANIFEST_SCHEMA_VERSION
                .to_owned(),
            id: ModelBundleId::parse(PROMPTED_SEGMENTATION_FIXTURE_BUNDLE_ID)
                .map_err(|error| provisioning(error.to_string()))?,
            version: Version::parse(FIXTURE_BUNDLE_VERSION)
                .map_err(|error| provisioning(error.to_string()))?,
            display_name: "Prompted Segmentation Fixture".to_owned(),
            description: Some(
                "Deterministic offline ONNX contract fixture; not SAM and not accuracy evidence"
                    .to_owned(),
            ),
            model_family: "AnnotAgent test fixture".to_owned(),
            architecture: "deterministic ONNX contract graph".to_owned(),
            format: ModelFormat::Onnx,
            variant: "fixture-only".to_owned(),
            capabilities: BTreeSet::from([ModelCapability::PromptedSegmentation]),
            compatible_plugins: vec![PluginCompatibilityRequirement {
                plugin_id: plugin.id.clone(),
                plugin_version: format!("={}", plugin.version),
                model_id: model.id.clone(),
                contract_hash: Sha256Digest::of_bytes(
                    &serde_json::to_vec(model).map_err(|error| provisioning(error.to_string()))?,
                ),
                required_file_roles: roles.clone(),
            }],
            files: vec![
                ModelBundleFile {
                    role: encoder_role.clone(),
                    path: "files/sam_image_encoder.onnx".to_owned(),
                    sha256: Sha256Digest::of_bytes(&encoder),
                    size_bytes: encoder.len() as u64,
                    external_data_files: Vec::new(),
                },
                ModelBundleFile {
                    role: decoder_role.clone(),
                    path: "files/sam_mask_decoder.onnx".to_owned(),
                    sha256: Sha256Digest::of_bytes(&decoder),
                    size_bytes: decoder.len() as u64,
                    external_data_files: Vec::new(),
                },
            ],
            contracts: vec![ModelContractReference {
                id: "sam-compatible-encoder-decoder-v1".to_owned(),
                path: "contracts/sam-compatible-v1.json".to_owned(),
                sha256: Sha256Digest::of_bytes(&contract_bytes),
                file_roles: roles,
            }],
            transforms: Vec::new(),
            source: ModelSourceMetadata {
                upstream_project: "AnnotAgent".to_owned(),
                upstream_model_id: PROMPTED_SEGMENTATION_FIXTURE_BUNDLE_ID.to_owned(),
                upstream_version: Some(FIXTURE_BUNDLE_VERSION.to_owned()),
                upstream_checkpoint_sha256: Some(Sha256Digest::of_bytes(
                    &[encoder.as_slice(), decoder.as_slice()].concat(),
                )),
                source_url: Some(
                    Url::parse("https://github.com/oooscarx/AnnotAgent")
                        .expect("repository URL is valid"),
                ),
            },
            export: ModelExportMetadata {
                exporter_name: "annotagent-rust-fixture-generator".to_owned(),
                exporter_version: env!("CARGO_PKG_VERSION").to_owned(),
                exporter_revision: None,
                export_date: None,
                opset: Some(13),
                numerical_validation: None,
            },
            runtime: ModelRuntimeMetadata {
                execution_providers: BTreeSet::from(["cpu".to_owned()]),
                platforms: plugin.compatibility.targets.iter().cloned().collect(),
                minimum_memory_mb: plugin.resources.minimum_memory_mb,
                recommended_memory_mb: plugin.resources.recommended_memory_mb,
            },
            license: ModelLicenseMetadata {
                name: "MIT".to_owned(),
                license_url: Some(
                    Url::parse("https://opensource.org/license/mit").expect("license URL is valid"),
                ),
                license_file: "licenses/MODEL-LICENSE".to_owned(),
                source_notice: Some("licenses/SOURCE-NOTICE".to_owned()),
                license_digest: Sha256Digest::of_bytes(FIXTURE_LICENSE.as_bytes()),
                redistribution: RedistributionStatus::Allowed,
                commercial_use: CommercialUseStatus::Allowed,
                requires_acceptance: false,
                usage_notes: vec![
                    "Fixture only; not SAM and not model-quality evidence".to_owned(),
                    "Cannot be bound into a publishable Workflow".to_owned(),
                ],
            },
            test_suite: ModelTestSuiteReference {
                test_id: "fixture-prompted-segmentation-v1".to_owned(),
                input_artifacts: vec![
                    "tests/input-image.png".to_owned(),
                    "tests/request.json".to_owned(),
                ],
                expected_summary: "tests/expected-summary.json".to_owned(),
                tolerances: "tests/tolerances.json".to_owned(),
            },
            fixture: true,
            publishable: false,
        };
        std::fs::write(
            staging.join(annotagent_model_bundle::MODEL_BUNDLE_MANIFEST_FILE),
            manifest
                .to_toml()
                .map_err(|error| provisioning(error.to_string()))?,
        )?;
        if let Some(parent) = package_path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        pack_model_bundle(&staging, package_path)
            .map_err(|error| provisioning(error.to_string()))?;
        Ok::<(), ModelCatalogError>(())
    })();
    let _ = std::fs::remove_dir_all(&staging);
    result
}

fn fixture_contract() -> Result<ModelContractDocument, ModelCatalogError> {
    let encoder =
        ModelFileRole::parse("image_encoder").map_err(|error| provisioning(error.to_string()))?;
    let decoder =
        ModelFileRole::parse("mask_decoder").map_err(|error| provisioning(error.to_string()))?;
    let tensor = |name: &str, shape: &[i64]| ModelTensorContract {
        name: name.to_owned(),
        aliases: BTreeSet::new(),
        dtype: "f32".to_owned(),
        shape: shape.to_vec(),
    };
    Ok(ModelContractDocument {
        contract_version: "1".to_owned(),
        roles: BTreeMap::from([
            (
                encoder.clone(),
                ModelFileTensorContract {
                    inputs: vec![tensor("input_image", &[1, 3, 1024, 1024])],
                    outputs: vec![tensor("image_embeddings", &[1, 256, 64, 64])],
                },
            ),
            (
                decoder.clone(),
                ModelFileTensorContract {
                    inputs: vec![
                        tensor("image_embeddings", &[1, 256, 64, 64]),
                        tensor("point_coords", &[1, 2, 2]),
                        tensor("point_labels", &[1, 2]),
                        tensor("mask_input", &[1, 1, 256, 256]),
                        tensor("has_mask_input", &[1]),
                        tensor("orig_im_size", &[2]),
                    ],
                    outputs: vec![
                        tensor("masks", &[1, 1, 256, 256]),
                        tensor("iou_predictions", &[1]),
                    ],
                },
            ),
        ]),
        connections: vec![ModelTensorConnection {
            source_role: encoder,
            source_output: "image_embeddings".to_owned(),
            target_role: decoder,
            target_input: "image_embeddings".to_owned(),
        }],
    })
}

fn fixture_smoke_request() -> Result<ModelBundleSmokeRequest, ModelCatalogError> {
    let image_id = ImageId(uuid::Uuid::nil());
    let detections = ArtifactRef {
        artifact_id: "fixture-source-detections".to_owned(),
        source_node: "fixture".to_owned(),
        port: "detections".to_owned(),
        artifact_type: ArtifactKind::DetectionSet,
        item_id: None,
    };
    let bbox =
        NormalizedRect::new(0.2, 0.2, 0.6, 0.6).map_err(|error| provisioning(error.to_string()))?;
    let detection = Detection::from_source(
        "fixture-object",
        Some("fixture-target".to_owned()),
        Some("fixture-target".to_owned()),
        Some(LabelId::from("fixture-target")),
        bbox,
        DetectionScore::relative(0.75).map_err(|error| provisioning(error.clone()))?,
        DetectionSource {
            model_id: "fixture-coarse-detector".to_owned(),
            capability: VisionCapability::ObjectDetection,
            artifact_id: detections.artifact_id.clone(),
        },
    )
    .map_err(|error| provisioning(error.clone()))?;
    Ok(ModelBundleSmokeRequest {
        image_path: "tests/input-image.png".to_owned(),
        operation: VisionCapability::PromptedSegmentation,
        input_artifacts: vec![
            PipelineArtifact::DetectionSet(DetectionSetArtifact {
                schema_version: annotagent_core::DETECTION_ARTIFACT_SCHEMA_VERSION,
                reference: detections.clone(),
                image_id,
                model_binding: "fixture-coarse-detector".to_owned(),
                validation_state: ArtifactValidationState::Unvalidated,
                detections: vec![detection.clone()],
                metadata: BTreeMap::from([("fixture".to_owned(), serde_json::json!(true))]),
            }),
            PipelineArtifact::BoxPromptSet(BoxPromptSetArtifact {
                reference: ArtifactRef {
                    artifact_id: "fixture-box-prompts".to_owned(),
                    source_node: "fixture".to_owned(),
                    port: "box_prompts".to_owned(),
                    artifact_type: ArtifactKind::BoxPromptSet,
                    item_id: None,
                },
                image_id,
                source_detections: detections.clone(),
                prompts: vec![BoxPrompt {
                    id: "fixture-box".to_owned(),
                    subject: detections.item("fixture-object"),
                    bbox,
                    attributes: BTreeMap::from([(
                        "source_detection".to_owned(),
                        serde_json::to_value(detection)
                            .map_err(|error| provisioning(error.to_string()))?,
                    )]),
                }],
            }),
        ],
        parameters: BTreeMap::from([
            ("multi_mask".to_owned(), serde_json::json!(false)),
            ("mask_threshold".to_owned(), serde_json::json!(0.0)),
        ]),
        timeout_ms: Some(120_000),
    })
}

fn provisioning(message: String) -> ModelCatalogError {
    ModelCatalogError::Provisioning(message)
}

#[derive(Clone, PartialEq, Message)]
struct ModelProto {
    #[prost(int64, tag = "1")]
    ir_version: i64,
    #[prost(string, tag = "2")]
    producer_name: String,
    #[prost(message, optional, tag = "7")]
    graph: Option<GraphProto>,
    #[prost(message, repeated, tag = "8")]
    opset_import: Vec<OperatorSetIdProto>,
}

#[derive(Clone, PartialEq, Message)]
struct OperatorSetIdProto {
    #[prost(string, tag = "1")]
    domain: String,
    #[prost(int64, tag = "2")]
    version: i64,
}

#[derive(Clone, PartialEq, Message)]
struct GraphProto {
    #[prost(message, repeated, tag = "1")]
    node: Vec<NodeProto>,
    #[prost(string, tag = "2")]
    name: String,
    #[prost(message, repeated, tag = "5")]
    initializer: Vec<TensorProto>,
    #[prost(message, repeated, tag = "11")]
    input: Vec<ValueInfoProto>,
    #[prost(message, repeated, tag = "12")]
    output: Vec<ValueInfoProto>,
}

#[derive(Clone, PartialEq, Message)]
struct NodeProto {
    #[prost(string, repeated, tag = "1")]
    input: Vec<String>,
    #[prost(string, repeated, tag = "2")]
    output: Vec<String>,
    #[prost(string, tag = "3")]
    name: String,
    #[prost(string, tag = "4")]
    op_type: String,
}

#[derive(Clone, PartialEq, Message)]
struct TensorProto {
    #[prost(int64, repeated, packed = "true", tag = "1")]
    dims: Vec<i64>,
    #[prost(int32, tag = "2")]
    data_type: i32,
    #[prost(float, repeated, packed = "true", tag = "4")]
    float_data: Vec<f32>,
    #[prost(int64, repeated, packed = "true", tag = "7")]
    int64_data: Vec<i64>,
    #[prost(string, tag = "8")]
    name: String,
}

#[derive(Clone, PartialEq, Message)]
struct ValueInfoProto {
    #[prost(string, tag = "1")]
    name: String,
    #[prost(message, optional, tag = "2")]
    r#type: Option<TypeProto>,
}

#[derive(Clone, PartialEq, Message)]
struct TypeProto {
    #[prost(message, optional, tag = "1")]
    tensor_type: Option<TypeProtoTensor>,
}

#[derive(Clone, PartialEq, Message)]
struct TypeProtoTensor {
    #[prost(int32, tag = "1")]
    elem_type: i32,
    #[prost(message, optional, tag = "2")]
    shape: Option<TensorShapeProto>,
}

#[derive(Clone, PartialEq, Message)]
struct TensorShapeProto {
    #[prost(message, repeated, tag = "1")]
    dim: Vec<TensorShapeDimension>,
}

#[derive(Clone, PartialEq, Message)]
struct TensorShapeDimension {
    #[prost(int64, tag = "1")]
    dim_value: i64,
}

fn value_info(name: &str, shape: &[i64]) -> ValueInfoProto {
    ValueInfoProto {
        name: name.to_owned(),
        r#type: Some(TypeProto {
            tensor_type: Some(TypeProtoTensor {
                elem_type: 1,
                shape: Some(TensorShapeProto {
                    dim: shape
                        .iter()
                        .map(|dimension| TensorShapeDimension {
                            dim_value: *dimension,
                        })
                        .collect(),
                }),
            }),
        }),
    }
}

fn float_initializer(name: &str, values: Vec<f32>) -> TensorProto {
    TensorProto {
        dims: vec![i64::try_from(values.len()).expect("Fixture tensor length fits i64")],
        data_type: 1,
        float_data: values,
        int64_data: Vec::new(),
        name: name.to_owned(),
    }
}

fn fixture_encoder_model() -> ModelProto {
    ModelProto {
        ir_version: 8,
        producer_name: "annotagent-rust-fixture".to_owned(),
        graph: Some(GraphProto {
            node: vec![NodeProto {
                input: vec!["embedding_shape".to_owned()],
                output: vec!["image_embeddings".to_owned()],
                name: "deterministic_embeddings".to_owned(),
                op_type: "ConstantOfShape".to_owned(),
            }],
            name: "fixture_image_encoder".to_owned(),
            initializer: vec![TensorProto {
                dims: vec![4],
                data_type: 7,
                float_data: Vec::new(),
                int64_data: vec![1, 256, 64, 64],
                name: "embedding_shape".to_owned(),
            }],
            input: vec![value_info("input_image", &[1, 3, 1024, 1024])],
            output: vec![value_info("image_embeddings", &[1, 256, 64, 64])],
        }),
        opset_import: vec![OperatorSetIdProto {
            domain: String::new(),
            version: 13,
        }],
    }
}

fn fixture_decoder_model() -> ModelProto {
    ModelProto {
        ir_version: 8,
        producer_name: "annotagent-rust-fixture".to_owned(),
        graph: Some(GraphProto {
            node: vec![
                NodeProto {
                    input: vec!["mask_input".to_owned(), "foreground".to_owned()],
                    output: vec!["masks".to_owned()],
                    name: "deterministic_mask".to_owned(),
                    op_type: "Add".to_owned(),
                },
                NodeProto {
                    input: vec!["fixture_score".to_owned()],
                    output: vec!["iou_predictions".to_owned()],
                    name: "deterministic_score".to_owned(),
                    op_type: "Identity".to_owned(),
                },
            ],
            name: "fixture_mask_decoder".to_owned(),
            initializer: vec![
                float_initializer("foreground", vec![1.0]),
                float_initializer("fixture_score", vec![0.75]),
            ],
            input: vec![
                value_info("image_embeddings", &[1, 256, 64, 64]),
                value_info("point_coords", &[1, 2, 2]),
                value_info("point_labels", &[1, 2]),
                value_info("mask_input", &[1, 1, 256, 256]),
                value_info("has_mask_input", &[1]),
                value_info("orig_im_size", &[2]),
            ],
            output: vec![
                value_info("masks", &[1, 1, 256, 256]),
                value_info("iou_predictions", &[1]),
            ],
        }),
        opset_import: vec![OperatorSetIdProto {
            domain: String::new(),
            version: 13,
        }],
    }
}

#[cfg(test)]
mod tests {
    use annotagent_model_bundle::verify_model_bundle;

    use super::*;

    #[test]
    fn built_in_fixture_is_deterministic_verified_and_non_publishable() {
        let temporary = tempfile::tempdir().expect("tempdir");
        let first = build_builtin_fixture_catalog(temporary.path()).expect("first");
        let digest = first.catalog.entries[0].bundle_sha256.clone();
        let second = build_builtin_fixture_catalog(temporary.path()).expect("second");
        assert_eq!(second.catalog.entries[0].bundle_sha256, digest);
        let verified = verify_model_bundle(&second.package_path).expect("verified");
        assert!(verified.manifest.fixture);
        assert!(!verified.manifest.publishable);
        assert_eq!(verified.manifest.files.len(), 2);

        let registry = crate::ModelBundleRegistry::open(temporary.path()).expect("registry");
        assert!(registry.catalogs().iter().any(|catalog| {
            catalog.catalog_id == BUILTIN_FIXTURE_CATALOG_ID
                && catalog.entries[0].bundle_id == verified.manifest.id
        }));
        assert_eq!(
            registry.local_catalog_bundle_path(
                BUILTIN_FIXTURE_CATALOG_ID,
                &verified.manifest.id,
                &verified.manifest.version,
            ),
            Some(second.package_path)
        );
    }
}
