import {randomUUID} from "node:crypto";
import {expect,test} from "./fixtures";

test("queued semantic planning binds exact consent, recovers receipts and preserves cumulative budget",async({request})=>{
  const project=`TEST-queue-planning-${Date.now()}`;
  expect((await request.post("/api/projects",{data:{id:project,yaml:"version: 1\nproject:\n  name: TEST queued planning\ndataset:\n  root: images\nruntime: {}\ntasks: []\nreview:\n  auto_accept_confidence: 0.9\n  force_review_below: 0.5\nexport:\n  formats: [native]\n"}})).ok()).toBe(true);
  const provider=await(await request.post("/api/providers",{data:{display_name:"TEST queue account",adapter:"open_ai_compatible",base_url:"http://127.0.0.1:8796/openai/v1"}})).json();
  expect((await request.post(`/api/providers/${provider.id}/credential`,{data:{source:"workspace_file",secret:"guided-e2e-protocol-fixture"}})).ok()).toBe(true);
  const model=await(await request.post("/api/model-profiles",{data:{provider_id:provider.id,display_name:"TEST queue planner",remote_model_id:"e2e-conversation-classification-schema-background",input_modalities:["text"],task_capabilities:["text_generation"],protocol_features:{tool_calls:true,structured_output:true}}})).json();
  expect((await request.post(`/api/providers/${provider.id}/active-probe`,{data:{model_profile_id:model.id,confirmed_billable:true}})).ok()).toBe(true);
  const conversation=(await(await request.post(`/api/projects/${project}/conversations`,{data:{}})).json()).conversation_id;
  const root=`/api/projects/${project}/conversations/${conversation}`;
  expect((await request.post(`${root}/agent-model`,{data:{request_id:randomUUID(),expected_revision:0,model_profile_id:model.id}})).ok()).toBe(true);
  const revision=(await(await request.get(`/api/projects/${project}/goal`)).json()).revision;
  const base={message:{id:randomUUID(),text:"TEST classify day and night",image:null},task_id:null as string|null,schema_revision:revision,mode:"plan"};
  const first=await(await request.post(`${root}/send`,{data:base})).json();
  const taskRoot=`${root}/tasks/${first.task_id}`;
  const supplement={...base,task_id:first.task_id,message:{...base.message,id:randomUUID(),text:"TEST distinguish cloudy afternoons"}};
  expect((await request.post(`${root}/send`,{data:supplement})).ok()).toBe(true);
  const path=`${taskRoot}/message-queue/${supplement.message.id}`;
  const preview=await(await request.get(`${path}/schema-preview`)).json();
  expect(preview.image_count).toBe(0);expect(preview.estimated_cost).toBeNull();expect(preview.maximum_calls).toBe(1);
  expect(await(await request.get(`${path}/schema-authorization`)).json()).toBeNull();
  expect((await(await request.get(`${taskRoot}/budget`)).json()).total_reserved_calls).toBe(0);
  const consent={call_id:randomUUID(),model_id:preview.model_id,scope_hash:preview.scope_hash,request_hash:preview.request_hash,previous_grant_id:preview.previous_grant_id,maximum_calls:preview.maximum_calls,expires_at:preview.expires_at,allow_unknown_cost:true};
  for(const changes of [{allow_unknown_cost:false},{maximum_calls:5},{request_hash:"e".repeat(64)},{model_id:randomUUID()},{execute:true}])expect((await request.post(`${path}/schema-proposals`,{data:{...consent,...changes}})).ok()).toBe(false);
  const running=request.post(`${path}/schema-proposals`,{data:consent});
  await expect.poll(async()=> (await(await request.get(`${taskRoot}/calls`)).json())[0]?.status).toBe("reserved");
  const duplicate=await request.post(`${path}/schema-proposals`,{data:consent});
  expect(duplicate.ok()).toBe(true);
  expect((await duplicate.json()).id).toBe(consent.call_id);
  expect(await(await request.get(`${taskRoot}/calls`)).json()).toHaveLength(1);
  expect((await request.post(`${path}/cancel`,{data:{}})).ok()).toBe(false);
  expect(await(await request.get(`${path}/schema-authorization`)).json()).toEqual(consent);
  const response=await running;expect(response.ok(),await response.text()).toBe(true);
  const receipt=await response.json();expect(receipt.status).toBe("completed");
  expect(await(await request.post(`${path}/schema-proposals`,{data:consent})).json()).toEqual(receipt);
  const draft=await(await request.get(`${taskRoot}/calls/${consent.call_id}/schema-draft`)).json();
  expect(draft.definition.goal).toContain(supplement.message.text);
  expect(draft.definition.goal).toContain(base.message.text);
  const next={...supplement,message:{...supplement.message,id:randomUUID(),text:"TEST another supplement"}};
  expect((await request.post(`${root}/send`,{data:next})).ok()).toBe(true);
  const nextPath=`${taskRoot}/message-queue/${next.message.id}`;
  expect((await request.post(`${nextPath}/schema-proposals`,{data:consent})).ok()).toBe(false);
  const nextPreview=await(await request.get(`${nextPath}/schema-preview`)).json();
  expect(nextPreview.used_calls).toBe(1);expect(nextPreview.maximum_calls).toBe(2);expect(nextPreview.previous_grant_id).toBe(consent.call_id);
  expect((await request.post(`${nextPath}/cancel`,{data:{}})).ok()).toBe(true);
  expect((await request.get(`${nextPath}/schema-preview`)).ok()).toBe(false);
  expect((await(await request.get(`${taskRoot}/budget`)).json()).total_reserved_calls).toBe(1);
  expect((await request.get(`/api/projects/foreign/conversations/${conversation}/tasks/${first.task_id}/message-queue/${supplement.message.id}/schema-authorization`)).ok()).toBe(false);
});
