import { randomUUID } from "node:crypto";
import { expect, test } from "./fixtures";
import type { SendCommand } from "../src/conversation-send";

test("Registry picker persists next-scope model without probes, sends or changing frozen scopes", async ({page,request}) => {
  test.setTimeout(120_000);
  const project = `TEST-model-picker-${Date.now()}`;
  expect((await request.post("/api/projects", {data:{id:project,yaml:"version: 1\nproject:\n  name: TEST model picker\ndataset:\n  root: images\nruntime: {}\ntasks: []\nreview:\n  auto_accept_confidence: 0.9\n  force_review_below: 0.5\nexport:\n  formats: [native]\n"}})).ok()).toBe(true);
  const models: {id:string;display_name:string}[]=[];
  for (const name of ["Alpha", "Beta"]) {
    const provider = await (await request.post("/api/providers",{data:{display_name:`TEST ${name} account`,adapter:"open_ai_compatible",base_url:"http://127.0.0.1:8796/openai/v1"}})).json();
    expect((await request.post(`/api/providers/${provider.id}/credential`,{data:{source:"workspace_file",secret:"guided-e2e-protocol-fixture"}})).ok()).toBe(true);
    const model = await (await request.post("/api/model-profiles",{data:{provider_id:provider.id,display_name:`TEST ${name} planner`,remote_model_id:name === "Alpha" ? "e2e-conversation-classification-schema-background" : "e2e-planner",input_modalities:["text"],task_capabilities:["text_generation"],protocol_features:{tool_calls:true,structured_output:true}}})).json();
    expect((await request.post(`/api/providers/${provider.id}/active-probe`,{data:{model_profile_id:model.id,confirmed_billable:true}})).ok()).toBe(true);
    models.push(model);
  }
  const conversation = (await (await request.post(`/api/projects/${project}/conversations`,{data:{}})).json()).conversation_id;
  const root = `/api/projects/${project}/conversations/${conversation}`;
  const revision = (await (await request.get(`/api/projects/${project}/goal`)).json()).revision;
  const send = await (await request.post(`${root}/send`,{data:{message:{id:randomUUID(),text:"TEST classify day and night",image:null},task_id:null,schema_revision:revision}})).json();
  const mutations:string[]=[];
  page.on("request", req=> {if(req.method()!=="GET")mutations.push(new URL(req.url()).pathname);});
  await page.goto(`/projects/${project}/work?conversation=${conversation}&task=${send.task_id}`);
  const composer = page.getByRole("textbox",{name:"Your message",exact:true});
  await composer.fill("TEST unsent text survives choosing a model");
  await page.getByLabel("Choose Agent model",{exact:true}).click();
  const picker = page.getByRole("combobox",{name:"Agent model",exact:true});
  await expect(picker).toBeEnabled();
  await picker.selectOption(models[0].id);
  await expect(picker).toBeEnabled();
  const original = await (await request.get(`${root}/tasks/${send.task_id}/schema-preview`)).json();
  expect(original.model_id).toBe(models[0].id);
  const search = page.getByRole("searchbox",{name:"Search models"});
  await search.fill("Beta"); await search.press("Enter");
  await expect(composer).toHaveValue("TEST unsent text survives choosing a model");
  await picker.selectOption(models[1].id);
  await expect(picker).toBeEnabled();
  const next = await (await request.get(`${root}/tasks/${send.task_id}/schema-preview`)).json();
  expect(next.model_id).toBe(models[1].id);
  expect(next.destination).toBeTruthy();
  const frozen = await (await request.get(`${root}/tasks/${send.task_id}/schema-preview?model_id=${models[0].id}`)).json();
  expect(frozen.model_id).toBe(original.model_id);
  expect(frozen.scope_hash).toBe(original.scope_hash);
  await page.screenshot({path:"/tmp/annotagent-agent-model-picker-desktop.png",fullPage:true});
  expect(mutations.every(path=>path.endsWith("/agent-model")),JSON.stringify(mutations)).toBe(true);
  await search.press("Escape");
  await expect(page.getByLabel("Choose Agent model",{exact:true})).toBeFocused();
  await composer.fill("");
  await page.reload();
  await page.getByLabel("Choose Agent model",{exact:true}).click();
  await expect(picker).toHaveValue(models[1].id);
  await page.setViewportSize({width:390,height:844});
  await expect(picker).toBeVisible();
  await page.screenshot({path:"/tmp/annotagent-agent-model-picker-mobile.png",fullPage:true});
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  expect((await (await request.get(`${root}/tasks/${send.task_id}/budget`)).json()).total_reserved_calls).toBe(0);
  // Explicit TEST-only authorization. Change preference while Alpha is actually
  // reserved in the backend; the late response must still be attributed to Alpha.
  const taskRoot = `${root}/tasks/${send.task_id}`;
  const before = await (await request.get(`${root}/agent-model`)).json();
  expect((await request.post(`${root}/agent-model`,{data:{request_id:randomUUID(),expected_revision:before.revision,model_profile_id:models[0].id}})).ok()).toBe(true);
  const consent = {call_id:randomUUID(),model_id:models[0].id,scope_hash:original.scope_hash,expires_at:original.expires_at,allow_unknown_cost:true};
  const running = request.post(`${taskRoot}/schema-proposals`,{data:consent});
  await expect.poll(async()=> (await (await request.get(`${taskRoot}/calls`)).json())[0]?.status).toBe("reserved");
  expect((await request.post(`${root}/agent-model`,{data:{request_id:randomUUID(),expected_revision:before.revision+1,model_profile_id:models[1].id}})).ok()).toBe(true);
  const launched = await running;
  expect(launched.ok(),await launched.text()).toBe(true);
  await expect.poll(async()=> (await (await request.get(`${taskRoot}/calls`)).json())[0]?.status).toBe("completed");
  const calls = await (await request.get(`${taskRoot}/calls`)).json();
  expect(calls).toHaveLength(1);
  expect(calls[0].id).toBe(consent.call_id);
  expect(calls[0].evidence.response.tool_calls[0].arguments.rationale).toContain("TEST received model: e2e-conversation-classification-schema-background");
  expect((await (await request.get(`${root}/agent-model`)).json()).model_profile_id).toBe(models[1].id);
  const observed = await (await request.get(`${root}/agent-model`)).json();
  const frozenMessage = {message:{id:randomUUID(),text:"TEST freeze Beta for this goal",image:null},task_id:null,schema_revision:revision,agent_model:observed};
  const captured = await (await request.post(`${root}/send`,{data:frozenMessage})).json();
  expect(captured.agent_model).toEqual(observed);
  expect((await request.post(`${root}/agent-model`,{data:{request_id:randomUUID(),expected_revision:observed.revision,model_profile_id:models[0].id}})).ok()).toBe(true);
  expect((await (await request.get(`${root}/tasks/${captured.task_id}/schema-preview`)).json()).model_id).toBe(models[1].id);
  expect(await (await request.post(`${root}/send`,{data:frozenMessage})).json()).toEqual(captured);
  const count = (await (await request.get(`${root}/messages`)).json()).length;
  const stale = await request.post(`${root}/send`,{data:{...frozenMessage,message:{...frozenMessage.message,id:randomUUID()}}});
  expect(stale.status()).toBe(409);
  expect((await stale.json()).code).toBe("send_model_selection_changed");
  expect((await (await request.get(`${root}/messages`)).json()).length).toBe(count);
  // The UI carries its observed revision. A different tab changes it before Send.
  await page.reload();
  await expect(page.getByLabel("Choose Agent model",{exact:true})).toContainText(models[0].display_name);
  const seen = await (await request.get(`${root}/agent-model`)).json();
  expect((await request.post(`${root}/agent-model`,{data:{request_id:randomUUID(),expected_revision:seen.revision,model_profile_id:models[1].id}})).ok()).toBe(true);
  const commands: SendCommand[]=[];
  page.on("request",req=>{if(req.method()==="POST"&&new URL(req.url()).pathname===`${root}/send`)commands.push(req.postDataJSON());});
  await composer.fill("TEST preserve this message across a model conflict");
  await page.getByRole("button",{name:"Send",exact:true}).click();
  await expect(page.getByRole("button",{name:"Review current model for this message",exact:true})).toBeVisible();
  expect(commands).toHaveLength(1);
  expect(commands[0].agent_model).toEqual(seen);
  await page.getByRole("button",{name:"Review current model for this message",exact:true}).click();
  await expect(page.getByRole("button",{name:"Send updated request",exact:true})).toBeEnabled();
  await expect(composer).toHaveValue("TEST preserve this message across a model conflict");
  expect(commands).toHaveLength(1);
  await page.getByRole("button",{name:"Send updated request",exact:true}).click();
  await expect(composer).toHaveValue("");
  expect(commands).toHaveLength(2);
  expect(commands[1].message.id).not.toBe(commands[0].message.id);
  expect({...commands[1].message,id:commands[0].message.id}).toEqual(commands[0].message);
  expect(commands[1].task_id).toBe(commands[0].task_id);
  expect(commands[1].schema_revision).toBe(commands[0].schema_revision);
  expect(commands[1].agent_model?.model_profile_id).toBe(models[1].id);
  expect((await (await request.get(`${root}/messages`)).json()).length).toBe(count+1);
});
