import { resolve } from "node:path";
import { randomUUID } from "node:crypto";
import { expect, test } from "./fixtures";

for(const scenario of ["classification","bbox","classification-review"] as const){
const kind = scenario === "bbox" ? "bbox" : "classification";
const requiresReview = scenario !== "classification";
test(`conversation ${scenario} authorizes HTTP fixture samples and restores editable terminal canvas`,async({page,request})=>{
  test.setTimeout(120_000);
  // Each scenario must bind its own TEST transport, not an earlier compatible registry model.
  const existingProfiles = (await (await request.get("/api/model-profiles")).json()).models;
  for (const profile of existingProfiles) {
    if (profile.display_name.startsWith("Conversation TEST ")) {
      expect((await request.patch(`/api/model-profiles/${profile.id}`, {data:{enabled:false}})).ok()).toBe(true);
    }
  }
  const provider=await (await request.post("/api/providers",{data:{display_name:"Conversation sample TEST transport",adapter:"open_ai_compatible",base_url:"http://127.0.0.1:8796/openai/v1"}})).json();
  expect((await request.post(`/api/providers/${provider.id}/credential`,{data:{source:"workspace_file",secret:"TEST-conversation-samples-only"}})).ok()).toBeTruthy();
  const model=await (await request.post("/api/model-profiles",{data:{provider_id:provider.id,display_name:`Conversation TEST ${scenario}`,remote_model_id:`e2e-conversation-${scenario}`,input_modalities:["text","image"],task_capabilities:["text_generation","vision_language","image_classification"],protocol_features:{tool_calls:true,structured_output:true}}})).json();
  expect((await request.post(`/api/providers/${provider.id}/active-probe`,{data:{model_profile_id:model.id,confirmed_billable:true}})).ok()).toBeTruthy();
  const defaults=await (await request.get("/api/agent-model-bindings")).json();
  expect((await request.put("/api/agent-model-bindings",{data:{...defaults,pipeline_builder:model.id}})).ok()).toBeTruthy();
  const project=`conversation-samples-${Date.now()}`;
  expect((await request.post("/api/projects",{data:{id:project,yaml:"version: 1\nproject:\n  name: TEST conversation samples\ndataset:\n  root: images\nruntime: {}\ntasks: []\nreview:\n  auto_accept_confidence: 0.9\n  force_review_below: 0.5\nexport:\n  formats: [native]\n"}})).ok()).toBeTruthy();
  expect((await request.put(`/api/projects/${project}/model-bindings`,{data:{bindings:[{capability:"image_classification",role:"classification",match_kind:"capability",model_profile_id:model.id,locked:false}]}})).ok()).toBeTruthy();
  await page.goto(`/projects/${project}/work`);
  await page.getByLabel("Add images",{exact:true}).setInputFiles(resolve("../examples/robocup/images/synthetic-robocup.png"));
  await expect(page.getByText("Images saved on this server. No model has been called.",{exact:true})).toBeVisible();
  await page.getByLabel("Your message",{exact:true}).fill(kind==="classification" ? "按室内和室外给图片分类" : "Find cups, not bottles. Draw a tight box around each cup.");
  await page.getByRole("button",{name:"Save message",exact:true}).click();
  await page.getByRole("button",{name:"Prepare label proposal",exact:true}).click();
  await page.getByRole("checkbox",{name:/Allow this text request/}).check();
  await page.getByRole("button",{name:"Generate label proposal",exact:true}).click();
  await page.getByRole("button",{name:"Save as editable Schema Draft",exact:true}).click();
  await page.getByRole("button",{name:"Review Builder authorization",exact:true}).click();
  await page.getByRole("checkbox",{name:/Allow this bounded Builder request/}).check();
  await page.getByRole("button",{name:"Build Pipeline Draft",exact:true}).click();
  await page.getByRole("button",{name:"Review sample authorization",exact:true}).click();
  const authorization=page.getByLabel("Sample model authorization",{exact:true});
  await expect(authorization).toContainText("Cost unknown");
  await page.getByRole("checkbox",{name:/Allow these sample images/}).check();
  const start=page.getByRole("button",{name:"Test these samples",exact:true});
  await expect(start).toBeEnabled();
  let envelope:any;
  await page.route(`**/api/projects/${project}/sample-operations`,async route=>{
    if(route.request().method()!=="POST")return route.continue();
    envelope=route.request().postDataJSON();
    await route.fetch();await route.abort("failed");
  },{times:1});
  await start.click();
  await expect(page.getByRole("button",{name:"View sample results in canvas",exact:true})).toBeVisible();
  expect(envelope.conversation.allow_unknown_cost).toBe(true);
  const taskRoot=`/api/projects/${project}/conversations/${envelope.conversation.conversation_id}/tasks/${envelope.conversation.task_id}`;
  const calls=await (await request.get(`${taskRoot}/calls`)).json();
  const initialReport = (await (await request.get(`/api/workflow-drafts/${envelope.draft_id}/sample-test?test_id=${envelope.request_id}`)).json()).sample_test.report;
  expect(initialReport.validation.valid).toBe(true);
  expect(initialReport.samples[0].nodes.some((node:any)=>node.metadata.model === `e2e-conversation-${scenario}`)).toBe(true);
  const processingPreviewResponse = await request.get(`/api/projects/${project}/processing-preview?draft_id=${envelope.draft_id}&sample_test_id=${envelope.request_id}`);
  expect(processingPreviewResponse.ok(), await processingPreviewResponse.text()).toBe(true);
  const processingPreview = await processingPreviewResponse.json();
  expect(processingPreview.conversation.conversation_id).toBe(envelope.conversation.conversation_id);
  expect(processingPreview.conversation.task_id).toBe(envelope.conversation.task_id);
  expect(processingPreview.conversation.schema.definition.task.kind).toBe(kind === "bbox" ? "bounding_box" : "classification");
  expect(processingPreview.goal.goal).toBe(processingPreview.conversation.schema.definition.goal);
  expect(await (await request.get(`${taskRoot}/processing-operations`)).json()).toEqual([]);
  expect((await request.get(taskRoot.replace(envelope.conversation.task_id, randomUUID()) + "/processing-operations")).ok()).toBe(false);
  expect(envelope.conversation.human_review).toBe(true);
  if(requiresReview){
  await expect.poll(async()=> (await (await request.get(`${taskRoot}/human-requests`)).json()).length).toBe(1);
  const initialAutomatic=(await (await request.get(`${taskRoot}/human-requests`)).json())[0];
  expect(initialAutomatic.input.reason_code).toBe("terminal_result_requires_review");
  expect(initialAutomatic.status).toBe("pending");
  await expect(page.getByText(initialAutomatic.input.question,{exact:true})).toBeVisible();
  // Retain explicit manual-request API coverage below without leaving a task budget blocker.
  expect((await request.post(`${taskRoot}/human-requests/${initialAutomatic.input.id}/cancel`)).ok()).toBe(true);
  } else {
    await expect.poll(async()=> (await (await request.get(`/api/projects/${project}/sample-operations/${envelope.request_id}`)).json()).assistance?.status).toBe("completed");
    expect(await (await request.get(`${taskRoot}/human-requests`)).json()).toEqual([]);
  }
  expect(calls.some((call:any)=>call.evidence?.phase==="sample_inference" && call.status==="completed")).toBe(true);
  if (requiresReview) {
    const saved = await (await request.get(`/api/workflow-drafts/${envelope.draft_id}/sample-test?test_id=${envelope.request_id}`)).json();
    const projection = saved.sample_test.report.samples[0].projection;
    expect(projection.final_candidates).toHaveLength(0);
    expect(projection.review_candidates).toHaveLength(1);
    expect(calls.filter((call:any) => call.evidence?.phase === "sample_inference")).toHaveLength(1);
  }
  const starts:string[]=[];
  page.on("request",request=>{if(request.method()==="POST")starts.push(request.url());});
  await page.reload();
  await page.getByRole("button",{name:"View sample results in canvas",exact:true}).click();
  await expect(page.getByLabel("Saved sample results",{exact:true})).toBeVisible();
  await expect(page.locator(".conversation-sample-canvas .annotation-canvas image")).toBeVisible();
  expect(new URL(page.url()).searchParams.get("test")).toBe(envelope.request_id);
  await page.reload();
  await expect(page.getByLabel("Saved sample results",{exact:true})).toBeVisible();
  expect(starts).toEqual([]);
  await page.getByRole("button",{name:"Annotation list · 1",exact:true}).click();
  await page.getByLabel("Annotations on canvas",{exact:true}).getByRole("button").first().click();
  if(kind==="classification")await page.getByLabel("Correct label",{exact:true}).fill("室外");
  else{await page.getByText("Result needs attention",{exact:true}).click();await page.getByRole("spinbutton",{name:"width",exact:true}).fill("0.15");}
  page.once("dialog",dialog=>dialog.dismiss());
  await page.getByRole("button",{name:"Back to project",exact:true}).click();
  expect(new URL(page.url()).searchParams.get("test")).toBe(envelope.request_id);
  if(kind==="classification")await expect(page.getByLabel("Correct label",{exact:true})).toHaveValue("室外");
  else await expect(page.getByRole("spinbutton",{name:"width",exact:true})).toHaveValue("0.15");
  await page.getByRole("button",{name:"Save sample feedback",exact:true}).click();
  await expect(page.getByText("Sample feedback saved",{exact:true})).toBeVisible();
  await page.reload();
  if(kind==="classification")await expect(page.getByLabel("Image classification results",{exact:true})).toContainText("室外");
  else {
    const box = page.locator(".conversation-sample-canvas .annotation-shape rect.aa-annotation-shape");
    await expect(box).toHaveCount(1);
    // Normalized geometry round-trips through Rust f32 before becoming SVG pixels.
    await expect.poll(async () => Number(await box.getAttribute("width"))).toBeCloseTo(96, 3);
  }
  expect(starts.filter(url=>!url.endsWith("/feedback"))).toEqual([]);
  expect(await (await request.get(`${taskRoot}/calls`)).json()).toEqual(calls);
  await page.locator(".conversation-image-panel").evaluate(element=>element.scrollTop=0);
  await page.screenshot({path:`../docs/execution/conversational-workspace/sample-${scenario}.png`,fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole("button",{name:/Images \(/}).click();
  await expect(page.getByLabel("Saved sample results",{exact:true})).toBeVisible();
  await page.screenshot({path:`../docs/execution/conversational-workspace/sample-${kind}-390.png`,fullPage:true});
  // A persisted request opens the existing canvas and saves through its atomic answer API.
  const imageId=new URL(page.url()).searchParams.get("image")!;
  const feedbackPath=`/api/workflow-sample-tests/${envelope.request_id}/images/${imageId}/feedback`;
  const revisions=(await (await request.get(feedbackPath)).json()).revisions;
  const previous=revisions.at(-1);
  const savedTest=(await (await request.get(`/api/workflow-drafts/${envelope.draft_id}/sample-test?test_id=${envelope.request_id}`)).json()).sample_test;
  const human={id:randomUUID(),task_id:envelope.conversation.task_id,conversation_id:envelope.conversation.conversation_id,sample_test_id:envelope.request_id,image_id:imageId,content_hash:savedTest.inputs.find((input:any)=>input.image_id===imageId).content_hash,outcome_id:previous.outcome_id,expected_feedback_sequence:previous.sequence,reason_code:"poor_boundary",question:"TEST: confirm this correction",resume_checkpoint_ref:randomUUID()};
  const humanRoot=`${taskRoot}/human-requests`;
  expect((await request.post(humanRoot,{data:{...human,task_id:randomUUID()}})).ok()).toBe(false);
  expect((await request.post(humanRoot,{data:human,headers:{Origin:"https://foreign.invalid"}})).status()).toBe(403);
  const created=await request.post(humanRoot,{data:human});
  expect(created.ok(),await created.text()).toBe(true);
  expect((await created.json()).status).toBe("pending");
  expect((await request.post(humanRoot,{data:human})).ok()).toBe(true);
  await page.setViewportSize({width:1280,height:800});
  await page.getByRole("button",{name:"Refresh requests",exact:true}).click();
  await page.locator("article").filter({hasText:human.question}).getByRole("button",{name:"Open requested result",exact:true}).click();
  await expect(page.getByRole("button",{name:"Submit correction",exact:true})).toBeVisible();
  expect(new URL(page.url()).searchParams.get("request")).toBe(human.id);
  expect(new URL(page.url()).searchParams.get("task")).toBe(human.task_id);
  await page.reload();
  await expect(page.getByRole("button",{name:"Submit correction",exact:true})).toBeVisible();
  await page.getByLabel("Correct label",{exact:true}).fill(kind==="classification" ? "室内" : "cup");
  if(kind==="bbox")await page.getByRole("spinbutton",{name:"width",exact:true}).fill("0.12");
  await page.locator(".conversation-panel").evaluate(element=>{const card=element.querySelector<HTMLElement>('[aria-label="Human requests"]');if(card)element.scrollTop=card.offsetTop-element.getBoundingClientRect().top;});
  await page.locator(".conversation-image-panel").evaluate(element=>element.scrollTop=0);
  await page.screenshot({path:`../docs/execution/conversational-workspace/human-request-${kind}.png`,fullPage:true});
  await page.setViewportSize({width:390,height:844});
  await page.getByRole("button",{name:/Images \(/}).click();
  await expect(page.getByRole("button",{name:"Submit correction",exact:true})).toBeVisible();
  await page.screenshot({path:`../docs/execution/conversational-workspace/human-request-${kind}-390.png`,fullPage:true});
  await page.setViewportSize({width:1280,height:800});
  let answer:any;
  await page.route(`**${humanRoot}/${human.id}/answer`,async route=>{answer=route.request().postDataJSON().answer;await route.fetch();await route.abort("failed");},{times:1});
  await page.getByRole("button",{name:"Submit correction",exact:true}).click();
  await expect(page.locator(".sample-confirm-action [role=alert]")).toBeVisible();
  if(kind==="bbox")await expect(page.getByRole("spinbutton",{name:"width",exact:true})).toHaveValue("0.12");
  else await expect(page.getByLabel("Correct label",{exact:true})).toHaveValue("室内");
  await page.getByRole("button",{name:"Submit correction",exact:true}).click();
  await expect(page.getByText("Correction saved and revision Draft prepared without model calls. Later repairs and tests have separate operation records.",{exact:true})).toBeVisible();
  expect(answer.outcome_id).toBe(human.outcome_id);
  expect(answer.sequence).toBe(previous.sequence+1);
  expect((await request.post(`${humanRoot}/${human.id}/answer`,{data:{answer}})).ok()).toBe(true);
  expect((await request.post(`${humanRoot}/${human.id}/answer`,{data:{answer:{...answer,note:"changed retry"}}})).ok()).toBe(false);
  expect((await (await request.get(feedbackPath)).json()).revisions).toHaveLength(revisions.length+1);
  await page.reload();
  const restored=(await (await request.get(humanRoot)).json()).filter((value:any)=>value.input.id===human.id);
  expect(restored).toHaveLength(1);
  expect(restored[0].answer.revision_id).toBe(answer.revision_id);
  expect(restored[0].status).toBe("applied");
  expect(restored[0].resume_draft_id).toBe(human.resume_checkpoint_ref);
  expect((await request.post(`${humanRoot}/${human.id}/resume`)).ok()).toBe(true);
  const evidence=await (await request.get(`/api/projects/${project}/sample-plan-copies/${human.resume_checkpoint_ref}`)).json();
  expect(evidence.feedback).toHaveLength(1);
  expect(evidence.feedback[0].revision_id).toBe(answer.revision_id);
  const cancelRequest={...human,id:randomUUID(),expected_feedback_sequence:answer.sequence};
  expect((await request.post(humanRoot,{data:cancelRequest})).ok()).toBe(true);
  const cancelled=await request.post(`${humanRoot}/${cancelRequest.id}/cancel`);
  expect(cancelled.ok()).toBe(true);
  expect((await cancelled.json()).status).toBe("cancelled");
  expect((await request.post(`${humanRoot}/${cancelRequest.id}/cancel`)).ok()).toBe(true);
  expect((await request.post(`${humanRoot}/${cancelRequest.id}/answer`,{data:{answer:{...answer,revision_id:randomUUID(),sequence:answer.sequence+1}}})).ok()).toBe(false);
  expect((await (await request.get(feedbackPath)).json()).revisions).toHaveLength(revisions.length+1);
  expect(await (await request.get(`${taskRoot}/calls`)).json()).toEqual(calls);
  const repairCard=page.getByRole("region",{name:"Repair annotation pipeline",exact:true});
  await expect(repairCard).toBeVisible();
  await repairCard.getByRole("button",{name:"Review Builder authorization",exact:true}).click();
  await expect(repairCard).toContainText("scoped human feedback and terminal result metadata");
  await expect(repairCard).toContainText("No image pixels");
  await repairCard.getByRole("checkbox",{name:/Allow this bounded Builder request/}).check();
  let repairConsent:any;
  page.on("request",req=>{if(req.method()==="POST" && req.url().endsWith(`${taskRoot}/builder-operations`))repairConsent=req.postDataJSON();});
  await repairCard.getByRole("button",{name:"Build Pipeline Draft",exact:true}).click();
  await expect(repairCard.getByText("Builder outcome saved",{exact:true})).toBeVisible({timeout:30_000});
  expect(repairConsent.selection.repair_request_id).toBe(human.id);
  expect(repairConsent.repair.draft_id).toBe(human.resume_checkpoint_ref);
  const repairCalls=await (await request.get(`${taskRoot}/calls`)).json();
  expect(repairCalls.length).toBeGreaterThan(calls.length);
  expect(repairCalls.length-calls.length).toBeLessThanOrEqual(8);
  const history=await (await request.get(`${taskRoot}/builder-operations`)).json();
  const repaired=history.items.find((item:any)=>item.operation.id===repairConsent.selection.operation_id);
  expect(repaired.session.working_draft.draft_id).toBe(human.resume_checkpoint_ref);
  expect(repaired.session.working_draft.build_mode.kind).toBe("repair_draft");
  expect((await request.post(`${taskRoot}/builder-operations`,{data:repairConsent})).ok()).toBe(true);
  await page.reload();
  await expect(repairCard.getByText("Builder outcome saved",{exact:true})).toBeVisible();
  expect(await (await request.get(`${taskRoot}/calls`)).json()).toEqual(repairCalls);
  await repairCard.getByRole("heading",{name:"Revise the plan from your correction",exact:true}).evaluate(element=>element.scrollIntoView({block:"start"}));
  await page.screenshot({path:`../docs/execution/conversational-workspace/repair-${kind}.png`,fullPage:true});
  await repairCard.getByRole("button",{name:"Review sample authorization",exact:true}).click();
  await repairCard.getByRole("checkbox",{name:/Allow these sample images/}).check();
  await repairCard.getByRole("button",{name:"Test these samples",exact:true}).click();
  await expect(repairCard.getByRole("button",{name:"View sample results in canvas",exact:true})).toBeVisible();
  await repairCard.getByRole("button",{name:"View sample results in canvas",exact:true}).click();
  await expect(page).toHaveURL(new RegExp(`draft=${human.resume_checkpoint_ref}`));
  const comparisonUrl=page.url();
  expect(new URL(comparisonUrl).searchParams.get("test")).not.toBe(human.sample_test_id);
  expect(new URL(comparisonUrl).searchParams.get("request")).toBe(human.id);
  expect(new URL(comparisonUrl).searchParams.get("task")).toBe(human.task_id);
  const afterComparison=await (await request.get(`${taskRoot}/calls`)).json();
  expect(afterComparison.length).toBeGreaterThan(repairCalls.length);
  await page.reload();
  await expect(page).toHaveURL(comparisonUrl);
  await expect(page.getByRole("heading",{name:"synthetic-robocup.png",exact:true})).toBeVisible();
  expect(await (await request.get(`${taskRoot}/calls`)).json()).toEqual(afterComparison);
  const origin=page.getByRole("complementary",{name:"Sample origin",exact:true});
  await expect(origin).toContainText("improvement has not been established");
  // A later whole-image note must not replace the request's selected subject on return.
  expect((await request.post(feedbackPath,{data:{...answer,revision_id:randomUUID(),sequence:answer.sequence+1,outcome_id:null,corrected_value:null,corrected_label:null,reason:"cannot_judge",note:"TEST unrelated whole-image note"}})).ok()).toBe(true);
  await origin.getByRole("button",{name:"Return to original correction",exact:true}).click();
  await expect(page).toHaveURL(new RegExp(`test=${human.sample_test_id}`));
  expect(new URL(page.url()).searchParams.get("image")).toBe(human.image_id);
  await expect(page.getByText("Correction saved and revision Draft prepared without model calls. Later repairs and tests have separate operation records.",{exact:true})).toBeVisible();
  await expect(page.getByLabel("Result to inspect",{exact:true})).toHaveValue(human.outcome_id);
  await page.goBack();
  await expect(page).toHaveURL(comparisonUrl);
  await expect(origin).toBeVisible();
  await origin.evaluate(element=>element.scrollIntoView({block:"start"}));
  await page.screenshot({path:`../docs/execution/conversational-workspace/comparison-origin-${kind}.png`,fullPage:true});
  expect(await (await request.get(`${taskRoot}/calls`)).json()).toEqual(afterComparison);
  if(kind==="bbox"){
  const comparisonId=new URL(comparisonUrl).searchParams.get("test");
  await expect.poll(async()=> (await (await request.get(humanRoot)).json()).filter((value:any)=>value.input.sample_test_id===comparisonId).length).toBe(1);
  const automatic=(await (await request.get(humanRoot)).json()).find((value:any)=>value.input.sample_test_id===comparisonId);
  expect(automatic.status).toBe("pending");
  const automaticCard=page.locator("article").filter({hasText:automatic.input.question}).filter({has:page.getByText("pending",{exact:true})});
  await expect(automaticCard).toBeVisible();
  await automaticCard.getByRole("button",{name:"Open requested result",exact:true}).click();
  await expect(page).toHaveURL(new RegExp(`request=${automatic.input.id}`));
  await expect(page.getByRole("button",{name:"Submit correction",exact:true})).toBeVisible();
  await page.getByRole("spinbutton",{name:"width",exact:true}).fill("0.14");
  await automaticCard.evaluate(element=>element.scrollIntoView({block:"start"}));
  await page.screenshot({path:"../docs/execution/conversational-workspace/automatic-human-request.png",fullPage:true});
  await page.getByRole("button",{name:"Submit correction",exact:true}).click();
  await expect.poll(async()=> (await (await request.get(humanRoot)).json()).find((value:any)=>value.input.id===automatic.input.id)?.status).toBe("applied");
  expect(await (await request.get(`${taskRoot}/calls`)).json()).toEqual(afterComparison);
  await page.reload();
  await expect(page.getByText("Correction saved and revision Draft prepared without model calls. Later repairs and tests have separate operation records.",{exact:true})).toBeVisible();
  expect(await (await request.get(`${taskRoot}/calls`)).json()).toEqual(afterComparison);
  }
  // Exercise the existing formal service using only this isolated HTTP TEST transport.
  const selection={draft_id:human.resume_checkpoint_ref,sample_test_id:new URL(comparisonUrl).searchParams.get("test"),limit:1};
  const approvalResponse=await request.get(`/api/projects/${project}/processing-preview?${new URLSearchParams(selection as any)}`);
  expect(approvalResponse.ok(),await approvalResponse.text()).toBe(true);
  const approval=await approvalResponse.json();
  const budgetBefore=await (await request.get(`${taskRoot}/budget`)).json();
  expect(budgetBefore.total_reserved_calls).toBe(afterComparison.length);
  await page.getByRole("button",{name:"Review dataset processing",exact:true}).click();
  const confirmCard=page.getByRole("region",{name:"Processing confirmation",exact:true});
  await expect(confirmCard).toContainText("prior usage is not reset");
  await expect(confirmCard).toContainText("Cost is unknown");
  await expect(confirmCard.getByRole("button",{name:"Confirm and start processing",exact:true})).toBeDisabled();
  await confirmCard.getByRole("checkbox",{name:"I authorize this image, model and call-budget scope",exact:true}).check();
  if(kind==="bbox"){
    await page.setViewportSize({width:390,height:844});
    await page.getByRole("button",{name:"Conversation",exact:true}).click();
    const authorizationCheckbox=confirmCard.getByRole("checkbox",{name:"I authorize this image, model and call-budget scope",exact:true});
    await authorizationCheckbox.scrollIntoViewIfNeeded();
    await expect(authorizationCheckbox).toBeChecked();
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true);
    await page.screenshot({path:"../docs/execution/conversational-workspace/processing-confirm-390.png",fullPage:true,animations:"disabled"});
    await page.setViewportSize({width:1280,height:800});
  }
  await confirmCard.evaluate(element=>element.scrollIntoView({block:"start"}));
  await page.screenshot({path:`../docs/execution/conversational-workspace/processing-confirm-${scenario}.png`,fullPage:true,animations:"disabled"});
  let confirmation:any;
  await page.route(`**/api/projects/${project}/processing-operations`,async route=>{
    confirmation=route.request().postDataJSON(); await route.fetch(); await route.abort("failed");
  },{times:1});
  await confirmCard.getByRole("button",{name:"Confirm and start processing",exact:true}).click();
  await expect.poll(()=>confirmation?.request_id).toBeTruthy();
  await expect(page).toHaveURL(new RegExp(`processing=${confirmation.request_id}`));
  await page.reload();
  await expect(confirmCard.getByRole("heading",{name:"Processing started",exact:true})).toBeVisible();
  const started=await (await request.get(`/api/projects/${project}/processing-operations/${confirmation.request_id}`)).json();
  expect(started.phase,JSON.stringify(started)).toBe("started");
  const duplicate=await (await request.post(`/api/projects/${project}/processing-operations`,{data:confirmation})).json();
  expect(duplicate.batch_id).toBe(started.batch_id);
  const operations=await (await request.get(`${taskRoot}/processing-operations`)).json();
  expect(operations).toHaveLength(1);
  expect(operations[0].authorization.conversation.schema.id).toBe(approval.conversation.schema.id);
  await expect.poll(async()=> (await (await request.get(`/api/batches/${started.batch_id}`)).json()).batch.images[0].execution_status).toBe(requiresReview ? "awaiting_review" : "completed");
  const frozenBatch=(await (await request.get(`/api/batches/${started.batch_id}`)).json()).checkpoint.batch;
  expect(frozenBatch.workflow_snapshot.settings.provider.max_retries).toBe(0);
  const budgetAfter=await (await request.get(`${taskRoot}/budget`)).json();
  expect(budgetAfter.planning_reserved_calls).toBe(budgetBefore.planning_reserved_calls);
  expect(budgetAfter.processing_authorized_calls).toBe(approval.maximum_model_calls);
  expect(budgetAfter.processing_reserved_calls).toBe(1);
  expect(budgetAfter.total_reserved_calls).toBe(budgetBefore.total_reserved_calls+1);
  expect(budgetAfter.total_authorized_calls).toBe(budgetBefore.total_authorized_calls+approval.maximum_model_calls);
  await page.reload();
  const processingCard=page.getByRole("region",{name:"Saved processing tasks",exact:true});
  await expect(processingCard.getByRole("button",{name:"Open processing results",exact:true})).toBeVisible();
  expect(new URL(page.url()).searchParams.get("test")).toBe(selection.sample_test_id);
  await processingCard.evaluate(element=>element.scrollIntoView({block:"start"}));
  await page.screenshot({path:`../docs/execution/conversational-workspace/processing-linked-${scenario}.png`,fullPage:true});
  const savedWorkspaceUrl=page.url();
  await processingCard.getByRole("button",{name:"Open processing results",exact:true}).click();
  await expect(page).toHaveURL(new RegExp(`/projects/${project}/batches/${started.batch_id}`));
  await expect(page.getByRole("region",{name:"Processing results",exact:true})).toBeVisible();
  await page.screenshot({path:`../docs/execution/conversational-workspace/processing-results-${scenario}.png`,fullPage:true,animations:"disabled"});
  await page.goBack();
  await expect(page).toHaveURL(savedWorkspaceUrl);
  await expect(page.getByRole("region",{name:"Saved processing tasks",exact:true})).toBeVisible();
  expect(await (await request.get(`${taskRoot}/processing-operations`)).json()).toHaveLength(1);
});
}
