import {randomUUID} from "node:crypto";
import {expect,test,fetchWithinMutationLimit} from "./fixtures";

test("Schema clarification is answered in the same task without another model call",async({page,request})=>{
  test.setTimeout(120_000);
  const provider=await (await request.post("/api/providers",{data:{display_name:"Clarification TEST",adapter:"open_ai_compatible",base_url:"http://127.0.0.1:8796/openai/v1"}})).json();
  expect((await request.post(`/api/providers/${provider.id}/credential`,{data:{source:"workspace_file",secret:"TEST-clarification-only"}})).ok()).toBe(true);
  const model=await (await request.post("/api/model-profiles",{data:{provider_id:provider.id,display_name:"Clarification TEST text",remote_model_id:"e2e-conversation-clarify",input_modalities:["text"],task_capabilities:["text_generation"],protocol_features:{tool_calls:true,structured_output:true}}})).json();
  expect((await request.post(`/api/providers/${provider.id}/active-probe`,{data:{model_profile_id:model.id,confirmed_billable:true}})).ok()).toBe(true);
  const defaults=await (await request.get("/api/agent-model-bindings")).json();
  expect((await request.put("/api/agent-model-bindings",{data:{...defaults,pipeline_builder:model.id}})).ok()).toBe(true);
  const project=`clarification-${Date.now()}`;
  expect((await request.post("/api/projects",{data:{id:project,yaml:"version: 1\nproject:\n  name: TEST clarification\ndataset:\n  root: images\nruntime: {}\ntasks: []\nreview:\n  auto_accept_confidence: 0.9\n  force_review_below: 0.5\nexport:\n  formats: [native]\n"}})).ok()).toBe(true);
  await page.goto(`/projects/${project}/work`);
  await page.getByLabel("Your message",{exact:true}).fill("TEST: annotate these images; help clarify the output");
  await page.getByRole("button",{name:"Save message",exact:true}).click();
  await page.getByRole("button",{name:"Prepare label proposal",exact:true}).click();
  await page.getByRole("checkbox",{name:/Allow this text request/}).check();
  await page.getByRole("button",{name:"Generate label proposal",exact:true}).click();
  await expect(page.getByText("Clarification needed",{exact:true})).toBeVisible();
  const conversation=(await (await request.get(`/api/projects/${project}/conversations`)).json()).conversation_id;
  const root=`/api/projects/${project}/conversations/${conversation}/tasks`;
  const tasks=await (await request.get(root)).json();expect(tasks).toHaveLength(1);
  const task=tasks[0],taskRoot=`${root}/${task.input.id}`;
  const calls=await (await request.get(`${taskRoot}/calls`)).json();
  const call=calls[0].id;
  const questionPath=`${taskRoot}/calls/${call}/clarification`;
  const question=await (await request.get(questionPath)).json();
  expect(question.status).toBe("pending");expect(question.kind).toBe("clarify_task");expect(question.task_id).toBe(task.input.id);
  const before=await (await request.get(`${taskRoot}/budget`)).json();
  await page.reload();
  await page.getByRole("button",{name:"Answer this clarification",exact:true}).click();
  await expect(page.getByLabel("Answer annotation clarification",{exact:true})).toContainText(question.question);
  await page.getByLabel("Output type",{exact:true}).selectOption("classification");
  await page.getByLabel("Labels · one per line",{exact:true}).fill("室内\n室外");
  await page.getByLabel("Boundary rules · optional",{exact:true}).fill("按相机所在环境分类，不按窗外的背景分类");
  let answer:any;
  await page.route(`**${taskRoot}/human-schema-drafts`,async route=>{answer=route.request().postDataJSON();const response=await fetchWithinMutationLimit(route);expect(response.ok(),await response.text()).toBe(true);await route.abort("failed");},{times:1});
  await page.getByRole("button",{name:"Save answer and continue",exact:true}).click();
  await page.getByRole("button",{name:"Retry same label save",exact:true}).click();
  await expect(page.getByRole("region",{name:"Saved label draft",exact:true})).toContainText("Revision 1");
  const applied=await (await request.get(questionPath)).json();expect(applied.status).toBe("applied");expect(applied.schema_draft_id).toBeTruthy();
  expect(answer.clarification).toEqual({call_id:call,expected_schema_revision:question.expected_schema_revision});
  expect((await request.post(`${taskRoot}/human-schema-drafts`,{data:{...answer,request_id:randomUUID()}})).ok()).toBe(false);
  expect((await request.post(`${taskRoot}/human-schema-drafts`,{data:{...answer,clarification:{...answer.clarification,expected_schema_revision:"stale"}}})).ok()).toBe(false);
  expect((await request.get(questionPath.replace(task.input.id,randomUUID()))).ok()).toBe(false);
  await page.reload();
  await expect(page.getByRole("region",{name:"Saved label draft",exact:true})).toContainText("Revision 1");
  await page.getByRole("button",{name:"Review Builder authorization",exact:true}).click();
  await expect(page.getByLabel("Builder model authorization",{exact:true})).toContainText("1 calls already used");
  expect(await (await request.get(`${taskRoot}/budget`)).json()).toEqual(before);
  expect(await (await request.get(root)).json()).toHaveLength(1);
  await page.getByRole("region",{name:"Saved label draft",exact:true}).screenshot({path:"../docs/execution/conversational-workspace/clarification-answer-restored.png",animations:"disabled"});
});
