import { randomUUID } from "node:crypto";
import { expect as baseExpect, test, fetchWithinMutationLimit } from "./fixtures";

// Match the fixture's bounded pacing of the shared server's 60-second mutation
// window; do not mistake an in-flight pre-execution 429 retry for a lost receipt.
const expect=baseExpect.configure({timeout:75_000});

test("authorized conversation Schema crosses actual HTTP Provider transport once and restores receipts", async ({ page, request }) => {
  test.setTimeout(180_000);
  const provider = await (await request.post("/api/providers", { data: { display_name:"Conversation TEST fixture", adapter:"open_ai_compatible",base_url:"http://127.0.0.1:8796/openai/v1" } })).json();
  expect((await request.post(`/api/providers/${provider.id}/credential`,{data:{source:"workspace_file",secret:"TEST-conversation-protocol-only"}})).ok()).toBeTruthy();
  const model = await (await request.post("/api/model-profiles",{data:{provider_id:provider.id,display_name:"Conversation TEST text model",remote_model_id:"e2e-conversation-schema",input_modalities:["text"],task_capabilities:["text_generation"],protocol_features:{tool_calls:true,structured_output:true}}})).json();
  expect((await request.post(`/api/providers/${provider.id}/active-probe`,{data:{model_profile_id:model.id,confirmed_billable:true}})).ok()).toBeTruthy();
  const project = `schema-test-${Date.now()}`;
  const yaml = "version: 1\nproject:\n  name: TEST schema transport\ndataset:\n  root: images\nruntime: {}\ntasks: []\nreview:\n  auto_accept_confidence: 0.9\n  force_review_below: 0.5\nexport:\n  formats: [native]\n";
  expect((await request.post("/api/projects",{data:{id:project,yaml}})).ok()).toBeTruthy();
  const root = `/api/projects/${project}/conversations`;
  const conversation = (await (await request.post(root)).json()).conversation_id;
  const revision = (await (await request.get(`/api/projects/${project}/goal`)).json()).revision;
  const limitPath=`/api/projects/${project}/conversation-call-limit`;
  expect((await request.post(limitPath,{data:{id:randomUUID(),expected_revision:0,maximum_calls:0}})).ok()).toBe(true);
  for (const [goal,kind] of [["Find cups, not bottles","bounding_box"],["按室内和室外给图片分类","classification"]]) {
    const message = randomUUID();
    expect((await request.post(`${root}/${conversation}/messages`,{data:{id:message,text:goal,image:null}})).ok()).toBeTruthy();
    const task = randomUUID();
    expect((await request.post(`${root}/${conversation}/tasks`,{data:{id:task,source_message_id:message,schema_revision:revision}})).ok()).toBeTruthy();
    const taskRoot = `${root}/${conversation}/tasks/${task}`;
    const previewResponse = await request.get(`${taskRoot}/schema-preview?model_id=${model.id}`);
    expect(previewResponse.ok()).toBeTruthy();
    const preview = await previewResponse.json();
    expect(preview.estimated_cost).toBeNull(); expect(preview.maximum_calls).toBe(1); expect(preview.image_count).toBe(0);
    const consent = {call_id:randomUUID(),model_id:model.id,scope_hash:preview.scope_hash,expires_at:preview.expires_at,allow_unknown_cost:true};
    expect((await request.post(`${taskRoot}/schema-proposals`,{data:{...consent,allow_unknown_cost:false}})).status()).toBe(400);
    expect((await request.post(`${taskRoot}/schema-proposals`,{data:{...consent,scope_hash:"stale"}})).status()).toBe(400);
    const beforeLimit=await (await request.get(limitPath)).json();
    const rejected=await request.post(`${taskRoot}/schema-proposals`,{data:consent});
    expect(rejected.ok()).toBe(false);expect(await rejected.text()).toContain("Project conversation call limit exhausted");
    expect((await (await request.get(limitPath)).json()).reserved_calls).toBe(beforeLimit.reserved_calls);
    expect(await (await request.get(`${taskRoot}/schema-authorizations/pending`)).json()).toEqual(consent);
    expect((await request.get(`${taskRoot.replace(task,randomUUID())}/schema-authorizations/pending`)).ok()).toBe(false);
    if(kind==="bounding_box"){
      await page.goto(`/projects/${project}/work?conversation=${conversation}&task=${task}`);
      await expect(page.getByRole("region",{name:"Annotation Schema proposal",exact:true})).toContainText("The original Schema request is saved, but no model call was admitted");
      await expect(page.getByText("Request recorded or being submitted.",{exact:false})).toHaveCount(0);
      await page.getByRole("button",{name:"Review saved Schema request",exact:true}).click();
      await expect(page.getByRole("button",{name:"Retry saved Schema request",exact:true})).toBeDisabled();
      await page.reload();
      await expect(page.getByLabel("Saved Schema authorization",{exact:true})).toContainText(consent.expires_at);
      await page.getByLabel("Saved Schema authorization",{exact:true}).screenshot({path:"../docs/execution/conversational-workspace/schema-pending-authorization.png",animations:"disabled"});
    }
    expect((await request.post(limitPath,{data:{id:randomUUID(),expected_revision:beforeLimit.revision,maximum_calls:beforeLimit.reserved_calls+1}})).ok()).toBe(true);
    if(kind==="bounding_box"){
      await page.getByRole("button",{name:"Review saved Schema request",exact:true}).click();
      await expect(page.getByRole("button",{name:"Retry saved Schema request",exact:true})).toBeEnabled();
      let actual:any;
      await page.route(`**${taskRoot}/schema-proposals`,async route=>{
        actual=route.request().postDataJSON();const saved=await fetchWithinMutationLimit(route);expect(saved.ok(),await saved.text()).toBe(true);await route.abort("failed");
      },{times:1});
      await page.getByRole("button",{name:"Retry saved Schema request",exact:true}).click();
      await expect(page.getByText("Schema proposal saved",{exact:true})).toBeVisible();
      await expect(page.getByRole("region",{name:"Annotation Schema proposal",exact:true}).getByRole("alert")).toHaveCount(0);
      expect(actual).toEqual(consent);
      await page.reload();await expect(page.getByText("Schema proposal saved",{exact:true})).toBeVisible();
      await page.getByRole("region",{name:"Annotation Schema proposal",exact:true}).screenshot({path:"../docs/execution/conversational-workspace/schema-original-consent-recovered.png",animations:"disabled"});
    }
    const response = await request.post(`${taskRoot}/schema-proposals`,{data:consent});
    expect(response.ok()).toBeTruthy(); const receipt = await response.json();
    expect(receipt.status).toBe("completed");
    expect(receipt.evidence.decision.Ok.kind).toBe(kind);
    expect(receipt.evidence.response.usage.total_tokens).toBe(48);
    expect((await (await request.post(`${taskRoot}/schema-proposals`,{data:consent})).json())).toEqual(receipt);
    expect((await (await request.get(`${taskRoot}/calls/${consent.call_id}`)).json())).toEqual(receipt);
    expect((await request.post(`${taskRoot}/schema-proposals`,{data:{...consent,call_id:randomUUID()}})).status()).toBe(400);
    const saveRoot = `${taskRoot}/calls/${consent.call_id}/schema-draft`;
    const automaticDraft=await (await request.get(saveRoot)).json();
    expect(automaticDraft.revision).toBe(1);
    expect(automaticDraft.source_call_id).toBe(consent.call_id);
    const savedResponse = await request.post(saveRoot);
    expect(savedResponse.ok()).toBeTruthy();
    const schemaDraft = await savedResponse.json();
    expect(schemaDraft).toEqual(automaticDraft);
    expect(schemaDraft.revision).toBe(1);
    expect(schemaDraft.definition.task.labels).toEqual(receipt.evidence.decision.Ok.labels);
    const draftRoot = `/api/projects/${project}/conversation-schema-drafts/${schemaDraft.id}`;
    const edit = {request_id:randomUUID(),expected_revision:1,decision:{...receipt.evidence.decision.Ok,labels:["TEST revised label"]}};
    const editedResponse = await request.post(draftRoot,{data:edit});
    expect(editedResponse.ok()).toBeTruthy();
    const edited = await editedResponse.json();
    expect(edited.revision).toBe(2);
    expect((await (await request.post(draftRoot,{data:edit})).json())).toEqual(edited);
    expect((await request.post(draftRoot,{data:{...edit,request_id:randomUUID()}})).status()).toBe(400);
    expect((await (await request.post(saveRoot)).json())).toEqual(edited);
    expect((await (await request.get(`${draftRoot}?revision=1`)).json())).toEqual(schemaDraft);
    expect((await (await request.get(draftRoot)).json())).toEqual(edited);
    const builderSelection = {operation_id:randomUUID(),schema_id:schemaDraft.id,schema_revision:2,model_id:model.id};
    const builderPreviewResponse = await request.get(`${taskRoot}/builder-preview`,{params:builderSelection});
    expect(builderPreviewResponse.ok()).toBeTruthy();
    const builderPreview = await builderPreviewResponse.json();
    expect(builderPreview.image_count).toBe(0); expect(builderPreview.estimated_cost).toBeNull();
    const builderConsent = {selection:builderPreview.selection,previous_grant_id:builderPreview.previous_grant_id,scope_hash:builderPreview.scope_hash,expires_at:builderPreview.expires_at,allow_unknown_cost:true};
    expect((await request.post(`${taskRoot}/builder-operations`,{data:{...builderConsent,allow_unknown_cost:false}})).status()).toBe(400);
    const builderResponse = await request.post(`${taskRoot}/builder-operations`,{data:builderConsent});
    expect(builderResponse.ok(),await builderResponse.text()).toBeTruthy();
    const operation = await builderResponse.json();
    expect(operation.status).toBe("completed"); expect(operation.evidence.samples_tested).toBe(false); expect(operation.evidence.published).toBe(false);
    expect((await (await request.post(`${taskRoot}/builder-operations`,{data:builderConsent})).json())).toEqual(operation);
    const restoredBuilder = await (await request.get(`${taskRoot}/builder-operations`)).json();
    expect(restoredBuilder.items[0].operation).toEqual(operation);
    expect(restoredBuilder.items[0].session.id).toBe(builderSelection.operation_id);
    const stoppedSelection={...builderSelection,operation_id:randomUUID()};
    const stopPreview=await (await request.get(`${taskRoot}/builder-preview`,{params:stoppedSelection})).json();
    const callsBeforeStop=await (await request.get(`${taskRoot}/calls`)).json();
    expect((await request.post(`${taskRoot}/calls/${stoppedSelection.operation_id}/cancel`)).ok()).toBeTruthy();
    const stoppedResponse=await request.post(`${taskRoot}/builder-operations`,{data:{selection:stopPreview.selection,previous_grant_id:stopPreview.previous_grant_id,scope_hash:stopPreview.scope_hash,expires_at:stopPreview.expires_at,allow_unknown_cost:true}});
    expect(stoppedResponse.status()).toBe(400);
    expect(await (await request.get(`${taskRoot}/calls`)).json()).toEqual(callsBeforeStop);
    const stoppedHistory=await (await request.get(`${taskRoot}/builder-operations`)).json();
    expect(stoppedHistory.items[0].operation.status).toBe("interrupted");
    expect(stoppedHistory.items[0].session).toBeNull();
  }
  expect((await (await request.get(`/api/projects/${project}/goal`)).json()).revision).toBe(revision);
  const defaults = await (await request.get("/api/agent-model-bindings")).json();
  expect((await request.put("/api/agent-model-bindings",{data:{...defaults,pipeline_builder:model.id}})).ok()).toBeTruthy();
  const uiProject = `${project}-ui`;
  expect((await request.post("/api/projects",{data:{id:uiProject,yaml}})).ok()).toBeTruthy();
  await page.goto(`/projects/${uiProject}/work`);
  await page.getByLabel("Your message",{exact:true}).fill("TEST find cups, not bottles");
  await page.getByRole("button",{name:"Save message",exact:true}).click();
  await page.getByRole("button",{name:"Prepare label proposal",exact:true}).click();
  await expect(page.getByLabel("Schema model authorization",{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Generate label proposal",exact:true})).toBeDisabled();
  await page.getByRole("checkbox",{name:/Allow this text request/}).check();
  await page.getByRole("button",{name:"Generate label proposal",exact:true}).click();
  await expect(page.getByText("Schema proposal saved",{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByText("Schema proposal saved",{exact:true})).toBeVisible();
  const originalProposal=page.locator(".conversation-proposal-details");
  await expect(originalProposal).not.toHaveAttribute("open", "");
  await expect(originalProposal.getByText("Object boxes",{exact:true})).toBeHidden();
  const proposalToggle=originalProposal.locator("summary");
  let detailWrites=0;
  const countDetailWrites=(req:{method:()=>string;url:()=>string})=>{
    if(!["GET","HEAD","OPTIONS"].includes(req.method())&&req.url().includes("/api/"))detailWrites++;
  };
  page.on("request",countDetailWrites);
  await proposalToggle.focus();
  await page.keyboard.press("Enter");
  await expect(originalProposal.getByText("Object boxes",{exact:true})).toBeVisible();
  await page.keyboard.press("Enter");
  await expect(originalProposal.getByText("Object boxes",{exact:true})).toBeHidden();
  await expect(proposalToggle).toBeFocused();
  page.off("request",countDetailWrites);
  expect(detailWrites).toBe(0);
  await expect(page.getByText("Schema Draft saved · Revision 1",{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Save as editable Schema Draft",exact:true})).toHaveCount(0);
  await page.getByRole("button",{name:"Edit labels and boundary rules",exact:true}).click();
  await page.getByLabel("Labels · one per line",{exact:true}).fill("TEST edited cup");
  await expect(page.getByText("Unsaved edits · Based on revision 1",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Save Schema changes",exact:true}).click();
  await expect(page.getByText("Schema Draft saved · Revision 2",{exact:true})).toBeVisible();
  let reloadWrites = 0;
  page.on("request",(req)=>{if(req.method()==="POST" && req.url().includes("/api/")) reloadWrites++;});
  await page.reload();
  await expect(page.getByText("Schema Draft saved · Revision 2",{exact:true})).toBeVisible();
  await expect(page.getByRole("region",{name:"Saved label draft"}).getByText("TEST edited cup",{exact:true})).toBeVisible();
  expect(reloadWrites).toBe(0);
  await page.getByRole("button",{name:"Edit labels and boundary rules",exact:true}).click();
  await page.getByLabel("Labels · one per line",{exact:true}).fill("TEST recovered edit");
  await page.route("**/conversation-schema-drafts/*",async(route)=>{
    const saved = await fetchWithinMutationLimit(route); expect(saved.ok(),await saved.text()).toBeTruthy(); await route.abort("failed");
  },{times:1});
  await page.getByRole("button",{name:"Save Schema changes",exact:true}).click();
  await expect(page.getByText("Save outcome unknown; retry the same edit",{exact:true})).toBeVisible();
  await expect(page.getByLabel("Labels · one per line",{exact:true})).toHaveValue("TEST recovered edit");
  await page.getByRole("button",{name:"Retry same Schema save",exact:true}).click();
  await expect(page.getByText("Schema Draft saved · Revision 3",{exact:true})).toBeVisible();
  await page.getByRole("button",{name:"Review Builder authorization",exact:true}).click();
  await expect(page.getByRole("button",{name:"Build Pipeline Draft",exact:true})).toBeDisabled();
  await page.getByRole("checkbox",{name:"Allow this bounded Builder request; actual cost is unknown",exact:true}).check();
  await page.route("**/builder-operations",async(route)=>{
    if(route.request().method()!=="POST"){await route.continue();return;}
    const response=await fetchWithinMutationLimit(route);expect(response.ok(),await response.text()).toBeTruthy();await route.abort("failed");
  },{times:1});
  await page.getByRole("button",{name:"Build Pipeline Draft",exact:true}).click();
  await expect(page.getByText("Builder outcome saved",{exact:true})).toBeVisible();
  const completedPlan=page.locator(".conversation-completed-stage > summary");
  if(await completedPlan.isVisible())await completedPlan.click();
  await expect(page.getByRole("link",{name:"Open saved Pipeline details",exact:true})).toHaveAttribute("href",new RegExp(`/projects/${uiProject}/build/pipeline\\?`));
  reloadWrites=0;
  await page.reload();
  await expect(page.getByText("Builder outcome saved",{exact:true})).toBeVisible();
  await expect(page.getByText("Schema proposal saved",{exact:true})).toBeVisible();
  expect(reloadWrites).toBe(0);
  for (const width of [1440,390]) {
    await page.setViewportSize({width,height:width===390?844:900});
    expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await page.screenshot({path:`../docs/execution/conversational-workspace/schema-${width}.png`,fullPage:true,animations:"disabled"});
  }
  const cancelProject = `${uiProject}-cancel`;
  const savedStage=page.locator(".conversation-completed-stage > summary");
  if(await savedStage.isVisible())await savedStage.click();
  await page.getByRole("button",{name:"Review another build request",exact:true}).click();
  await page.getByRole("checkbox",{name:"Allow this bounded Builder request; actual cost is unknown",exact:true}).check();
  let releaseBuilder!:()=>void;
  const holdBuilder=new Promise<void>((resolve)=>{releaseBuilder=resolve;});
  await page.route("**/builder-operations",async(route)=>{if(route.request().method()==="POST")await holdBuilder;await route.fallback();});
  const builderSubmitted=page.waitForRequest((req)=>req.method()==="POST" && req.url().endsWith("/builder-operations"));
  await page.getByRole("button",{name:"Build Pipeline Draft",exact:true}).click();
  const builderPending=await builderSubmitted;
  await page.getByRole("button",{name:"Stop Builder",exact:true}).click();
  await expect(page.getByText(/^Cancellation saved\. Waiting for the server/)).toBeVisible();
  const builderStopped=page.waitForResponse((res)=>res.url()===builderPending.url() && res.request().method()==="POST");
  releaseBuilder();expect((await builderStopped).status()).toBe(400);
  await page.unroute("**/builder-operations");
  await expect(page.getByText("Build interrupted",{exact:true})).toBeVisible();
  await page.reload();
  await expect(page.getByText("Build interrupted",{exact:true})).toBeVisible();
  await expect(page.getByRole("button",{name:"Stop Builder",exact:true})).toHaveCount(0);
  await page.screenshot({path:"../docs/execution/conversational-workspace/builder-cancelled.png",fullPage:true,animations:"disabled"});
  expect((await request.post("/api/projects",{data:{id:cancelProject,yaml}})).ok()).toBeTruthy();
  await page.setViewportSize({width:1440,height:900});
  await page.goto(`/projects/${cancelProject}/work`);
  await page.getByLabel("Your message",{exact:true}).fill("TEST cancel before sending");
  await page.getByRole("button",{name:"Save message",exact:true}).click();
  const cancelLimit=`/api/projects/${cancelProject}/conversation-call-limit`;
  expect((await request.post(cancelLimit,{data:{id:randomUUID(),expected_revision:0,maximum_calls:0}})).ok()).toBe(true);
  await page.getByRole("button",{name:"Prepare label proposal",exact:true}).click();
  await page.getByRole("checkbox",{name:/Allow this text request/}).check();
  await expect(page.getByRole("button",{name:"Generate label proposal",exact:true})).toBeDisabled();
  await expect(page.getByLabel("Schema model authorization",{exact:true})).toContainText("Project call limit exhausted");
  expect((await request.post(cancelLimit,{data:{id:randomUUID(),expected_revision:1,maximum_calls:1}})).ok()).toBe(true);
  let releaseRefresh!:()=>void;
  const refreshHeld=new Promise<void>(resolve=>{releaseRefresh=resolve;});
  await page.route("**/schema-preview*",async route=>{await refreshHeld;await route.fallback();},{times:1});
  await page.getByLabel("Schema model authorization",{exact:true}).getByRole("button",{name:"Refresh authorization and Project budget",exact:true}).click();
  await expect(page.getByRole("checkbox",{name:/Allow this text request/})).not.toBeChecked();
  await expect(page.getByRole("checkbox",{name:/Allow this text request/})).toBeDisabled();
  releaseRefresh();
  await expect(page.getByLabel("Schema model authorization",{exact:true})).toContainText("Project has 1 calls remaining");
  await page.getByRole("checkbox",{name:/Allow this text request/}).check();
  let release!: () => void;
  const held = new Promise<void>((resolve)=>{release=resolve;});
  await page.route("**/schema-proposals",async(route)=>{await held;await route.fallback();},{times:1});
  const submitted = page.waitForRequest((req)=>req.method()==="POST" && req.url().endsWith("/schema-proposals"));
  await page.getByRole("button",{name:"Generate label proposal",exact:true}).click();
  const pending = await submitted;
  await page.getByRole("button",{name:"Stop Schema request",exact:true}).click();
  await expect(page.getByText(/^Cancellation saved/)).toBeVisible({timeout:70_000});
  const rejected = page.waitForResponse((res)=>res.url()===pending.url());
  release(); expect((await rejected).status()).toBe(400);
  await page.reload();
  await expect(page.getByText(/^Cancellation saved/)).toBeVisible({timeout:70_000});
  await expect(page.getByRole("button",{name:"Prepare label proposal",exact:true})).toHaveCount(0);
  await expect(page.getByText("Schema proposal saved",{exact:true})).toHaveCount(0);
  await page.screenshot({path:"../docs/execution/conversational-workspace/schema-cancelled.png",fullPage:true,animations:"disabled"});
});
