import { resolve } from "node:path";
import { expect, test } from "./fixtures";

test("conditional model connection saves, verifies with consent, and returns without inference", async ({ page, request }) => {
  const charged: string[] = [];
  const createdProviders: string[] = [];
  page.on("request", (req) => { if (req.method() === "POST" && req.url().endsWith("/api/providers")) createdProviders.push(req.url()); });
  page.on("request", (req) => { if (req.method() === "POST" && /active-probe|suggest|dry-run/.test(req.url())) charged.push(req.url()); });
  await page.route("**/api/agent-model-bindings", (route) => route.fulfill({ json: {} }));
  // Isolate the catalog presented to this test from other suite-created connections.
  await page.route("**/api/model-profiles", async (route) => {
    if (route.request().method() !== "GET") return route.continue();
    const response = await route.fetch(); const body = await response.json();
    await route.fulfill({ json: { ...body, models: body.models.filter((model: { display_name: string }) => ["e2e-pipeline-builder", "e2e-journey-classifier"].includes(model.display_name)) } });
  });
  await page.goto("/projects?new=1");
  await page.getByLabel("Choose images", { exact: true }).setInputFiles(resolve("../examples/robocup/images/synthetic-robocup.png"));
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await expect(page).toHaveURL(/\/task\/goal$/);
  const projectId = new URL(page.url()).pathname.split("/")[2];
  await page.getByLabel("Describe your goal", { exact: true }).fill("TEST classify day scenes");
  await page.getByLabel("Categories to keep", { exact: true }).fill("day, night");
  await page.getByRole("radio", { name: /Image categories/ }).check();
  await page.getByRole("button", { name: "Save goal and connect model", exact: true }).click();
  await expect(page).toHaveURL(/\/task\/model$/);
  await page.getByRole("button", { name: "Connect a model service", exact: true }).click();
  await page.getByLabel("Service URL", { exact: true }).fill("http://127.0.0.1:8796/openai/v1");
  await page.getByLabel("Model name from your service", { exact: true }).fill("e2e-pipeline-builder");
  await page.getByLabel("API key", { exact: true }).fill("journey-test-only-fixture-credential");
  await page.getByRole("checkbox", { name: "This text model supports tool calls and structured responses" }).check();
  await page.getByRole("button", { name: "Save connection", exact: true }).click();
  await expect(page.getByRole("region", { name: "Connection verification", exact: true })).toBeVisible();
  expect(charged).toEqual([]);
  await expect(page.getByRole("button", { name: "Use connection and return", exact: true })).toBeDisabled();
  await page.getByRole("checkbox", { name: "Allow the text verification request", exact: true }).check();
  await page.getByRole("button", { name: "Verify connection", exact: true }).click();
  await expect(page.getByRole("button", { name: "Use connection and return", exact: true })).toBeEnabled();
  expect(charged).toHaveLength(1);
  const modelSelection = page.getByRole("radio", { checked: true });
  await expect(modelSelection).toHaveCount(1);
  await page.reload();
  // The saved connection survives refresh, but a GET never silently chooses or probes it.
  await page.getByRole("radio", { name: /e2e-pipeline-builder/ }).last().check();
  expect(charged).toHaveLength(1);
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: width === 390 ? 844 : 900 });
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await page.screenshot({ path: `../docs/execution/guided-journey/model-${width}.png`, fullPage: true });
  }
  await page.getByRole("button", { name: "Use connection and return", exact: true }).click();
  await expect(page).toHaveURL(`/projects/${projectId}/task/goal`);
  await expect(page.getByLabel("Categories to keep", { exact: true })).toHaveValue("day, night");
  await expect(page.getByRole("button", { name: "Connect an image model", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Connect an image model", exact: true }).click();
  await expect(page).toHaveURL(/\/task\/model\?purpose=vision$/);
  await expect(page.getByRole("radio", { name: /e2e-pipeline-builder/ })).toHaveCount(0);
  await page.getByRole("button", { name: "Back to saved goal", exact: true }).click();
  await expect(page.getByLabel("Categories to keep", { exact: true })).toHaveValue("day, night");
  expect(charged).toHaveLength(1);
  await page.getByRole("button", { name: "Connect an image model", exact: true }).click();
  await page.getByRole("button", { name: "Connect a model service", exact: true }).click();
  await page.getByLabel("Service URL", { exact: true }).fill("http://127.0.0.1:8796/openai/v1");
  await page.getByLabel("Model name from your service", { exact: true }).fill("e2e-journey-classifier");
  await page.getByLabel("API key", { exact: true }).fill("journey-test-only-fixture-credential");
  await page.getByRole("checkbox", { name: "This model accepts images and supports my selected output type with structured responses" }).check();
  await page.route("**/api/model-profiles", (route) => route.fulfill({ status: 503, json: { error: "TEST fixture: model setup interrupted" } }), { times: 1 });
  await page.getByRole("button", { name: "Save connection", exact: true }).click();
  await expect(page.getByRole("alert")).toContainText("model setup interrupted");
  await page.reload();
  await expect(page.getByLabel("Service URL", { exact: true })).toHaveValue("http://127.0.0.1:8796/openai/v1");
  await expect(page.getByLabel("API key", { exact: true })).toBeEmpty();
  await page.getByLabel("Model name from your service", { exact: true }).fill("e2e-journey-classifier");
  await page.getByRole("checkbox", { name: "This model accepts images and supports my selected output type with structured responses" }).check();
  await page.getByRole("button", { name: "Save connection", exact: true }).click();
  await expect(page.getByRole("region", { name: "Connection verification", exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("region", { name: "Connection verification", exact: true })).toBeVisible();
  expect(charged).toHaveLength(1);
  await page.getByRole("checkbox", { name: "Allow the text verification request", exact: true }).check();
  await page.getByRole("button", { name: "Verify connection", exact: true }).click();
  await expect(page.getByRole("button", { name: "Use connection and return", exact: true })).toBeEnabled();
  await page.getByRole("button", { name: "Use connection and return", exact: true }).click();
  await expect(page).toHaveURL(`/projects/${projectId}/task/goal`);
  await expect(page.getByRole("button", { name: "Prepare sample results", exact: true })).toBeEnabled();
  await page.reload();
  await expect(page.getByLabel("Describe your goal", { exact: true })).toHaveValue("TEST classify day scenes");
  const bindings = await (await request.get(`/api/projects/${projectId}/model-bindings`)).json();
  expect(bindings.bindings.some((binding: { role: string }) => binding.role === "pipeline_builder")).toBe(true);
  expect(bindings.bindings.some((binding: { role: string }) => binding.role === "classification")).toBe(true);
  expect(charged).toHaveLength(2);
  expect(createdProviders).toHaveLength(2);
  await expect(page.locator(".sidebar, .provider-table, .workflow-edit-details, .focus-project-menu")).toHaveCount(0);
});
