import { resolve } from "node:path";
import { expect, test } from "./fixtures";

test("ready fixture journey plans without image calls then authorizes a bounded sandbox test", async ({ page, request }) => {
  test.setTimeout(120_000);
  const provider = await (await request.post("/api/providers", { data: { display_name: "Journey TEST fixture", adapter: "open_ai_compatible", base_url: "http://127.0.0.1:8796/openai/v1" } })).json();
  expect((await request.post(`/api/providers/${provider.id}/credential`, { data: { source: "workspace_file", secret: "guided-e2e-protocol-fixture" } })).ok()).toBeTruthy();
  const model = await (await request.post("/api/model-profiles", { data: {
    provider_id: provider.id, display_name: "Journey TEST model", remote_model_id: "e2e-slow-sample",
    input_modalities: ["text", "image"], task_capabilities: ["text_generation", "vision_language", "image_classification"], protocol_features: { tool_calls: true, structured_output: true },
  } })).json();
  expect((await request.post(`/api/providers/${provider.id}/active-probe`, { data: { model_profile_id: model.id, confirmed_billable: true } })).ok()).toBeTruthy();
  const defaults = await (await request.get("/api/agent-model-bindings")).json();
  expect((await request.put("/api/agent-model-bindings", { data: { ...defaults, pipeline_builder: model.id } })).ok()).toBeTruthy();
  const sampleRequests: unknown[] = [];
  page.on("request", (req) => { if (req.method() === "POST" && req.url().endsWith("/sample-operations")) sampleRequests.push(req.postDataJSON()); });
  await page.goto("/projects?new=1");
  await page.getByLabel("Choose images", { exact: true }).setInputFiles(resolve("../examples/robocup/images/synthetic-robocup.png"));
  await page.getByRole("button", { name: "Continue", exact: true }).click();
  await expect(page).toHaveURL(/\/task\/goal$/);
  const projectId = new URL(page.url()).pathname.split("/")[2];
  expect((await request.put(`/api/projects/${projectId}/model-bindings`, { data: { bindings: [{ capability: "image_classification", role: "classification", match_kind: "capability", model_profile_id: model.id, locked: false }] } })).ok()).toBeTruthy();
  await page.getByLabel("Describe your goal", { exact: true }).fill("Classify the scene as day.");
  await page.getByRole("radio", { name: /Image categories/ }).check();
  await page.getByLabel("Categories to keep", { exact: true }).fill("day");
  await page.getByRole("button", { name: "Prepare sample results", exact: true }).click();
  await expect(page.getByRole("region", { name: "Planning authorization" })).toBeVisible();
  expect(sampleRequests).toEqual([]);
  await page.getByRole("button", { name: "Authorize planning", exact: true }).click();
  await expect(page).toHaveURL(/\/task\/samples\?draft=/, { timeout: 60_000 });
  await expect(page.getByRole("region", { name: "Sample authorization" })).toBeVisible();
  const draftId = new URL(page.url()).searchParams.get("draft")!;
  const sessions = await (await request.get(`/api/projects/${projectId}/agent-sessions`)).json();
  expect(sessions.sessions[0].builder_constraints.maximum_dry_runs).toBe(0);
  expect(sessions.sessions[0].outcome).toBe("draft_ready_for_human_review");
  expect(sessions.sessions[0].steps.every((step: { success: boolean }) => step.success)).toBe(true);
  expect(sessions.sessions[0].steps.filter((step: { tool_name: string; success: boolean }) => step.tool_name === "dry_run_pipeline" && step.success)).toHaveLength(0);
  const preview = await (await request.get(`/api/workflow-drafts/${draftId}/sample-preview`)).json();
  expect(preview.supported, JSON.stringify(preview)).toBe(true);
  expect(preview.request_limit).toBe(12);
  const prematurePublication = await request.post(`/api/workflow-drafts/${draftId}/publish`, { data: {} });
  expect(prematurePublication.ok()).toBe(false);
  expect(await prematurePublication.text()).toContain("persisted Sample Test");
  const stale = await request.post(`/api/workflow-drafts/${draftId}/dry-run`, { data: { image_indices: [0], expected_revision: preview.revision, authorization_fingerprint: "stale-scope" } });
  expect(stale.status()).toBe(400);
  await page.getByRole("checkbox", { name: "I reviewed the sample scope" }).check();
  await page.getByRole("button", { name: "Test samples", exact: true }).click();
  await expect(page).toHaveURL(/operation=/);
  await expect(page.getByRole("button", { name: "Stop sample test", exact: true })).toBeVisible();
  await expect(page.getByRole("region", { name: "Sample input previews" }).getByRole("img")).toBeVisible();
  const operationUrl = page.url();
  await page.screenshot({ path: "../docs/execution/guided-journey/sample-running.png", fullPage: true });
  const operationId = new URL(operationUrl).searchParams.get("operation")!;
  const duplicate = await request.post(`/api/projects/${projectId}/sample-operations`, { data: sampleRequests[0] });
  expect(duplicate.ok()).toBe(true);
  expect((await duplicate.json()).id).toBe(operationId);
  const sameRequest = sampleRequests[0] as Record<string, unknown>;
  expect((await request.post(`/api/projects/${projectId}/sample-operations`, { data: { ...sameRequest, expected_revision: Number(sameRequest.expected_revision) + 1 } })).status()).toBe(400);
  expect((await request.post(`/api/projects/${projectId}/sample-operations`, { data: { ...sameRequest, request_id: crypto.randomUUID(), authorization_fingerprint: "changed-scope" } })).status()).toBe(400);
  expect((await request.get(`/api/projects/wrong-project/sample-operations/${operationId}`)).status()).toBe(404);
  await page.reload();
  expect(sampleRequests).toHaveLength(1);
  await expect(page.getByRole("heading", { name: "Does this result match what you need?" })).toBeVisible();
  expect(sampleRequests).toHaveLength(1);
  await expect(page.locator(".sample-feedback-image svg image")).toBeVisible();
  await expect(page.locator(".sample-technical-details, .sample-diagnostics, .workflow-edit-details, .build-steps, .sidebar, .focus-project-menu")).toHaveCount(0);
  const resultUrl = page.url();
  await page.reload();
  await expect(page.locator(".sample-feedback-image svg image")).toBeVisible();
  await expect(page).toHaveURL(resultUrl);
  expect(sampleRequests).toHaveLength(1);
  for (const [width, height] of [[1440, 900], [1280, 720], [1024, 768], [390, 844]]) {
    await page.setViewportSize({ width, height });
    expect(await page.evaluate(() => document.documentElement.scrollWidth)).toBeLessThanOrEqual(width);
    await page.screenshot({ path: `../docs/execution/guided-journey/sample-${width}.png`, fullPage: true });
  }
  const annotations = await (await request.get(`/api/projects/${projectId}/export-readiness`)).json();
  expect(JSON.stringify(annotations)).not.toContain("human_accepted");
  // A persisted planning session is a read-only recovery key, never a request to re-plan.
  const planningRequests: string[] = [];
  page.on("request", (req) => { if (req.method() === "POST" && req.url().endsWith("/suggest")) planningRequests.push(req.url()); });
  await page.goto(`/projects/${projectId}/task/goal?session=${sessions.sessions[0].id}`);
  await expect(page).toHaveURL(/\/task\/samples\?/, { timeout: 20_000 });
  expect(planningRequests).toEqual([]);
  expect(sampleRequests).toHaveLength(1);
  await page.goto(`/projects/${projectId}/task/goal?session=missing-session`);
  await expect(page.getByRole("alert")).toContainText("This planning task does not exist in this Project");
  await expect(page).toHaveURL(/session=missing-session/);
  expect(planningRequests).toEqual([]);
  // A second explicitly authorized test can be stopped without advancing or formal writes.
  const nextPreview = await (await request.get(`/api/workflow-drafts/${draftId}/sample-preview`)).json();
  const stoppedId = crypto.randomUUID();
  const stopInput = { request_id: stoppedId, draft_id: draftId, image_indices: [0], expected_revision: nextPreview.revision, authorization_fingerprint: nextPreview.authorization_fingerprint };
  expect((await request.post(`/api/projects/${projectId}/sample-operations`, { data: stopInput })).ok()).toBe(true);
  await page.goto(`/projects/${projectId}/task/samples?draft=${draftId}&operation=${stoppedId}`);
  await page.getByRole("button", { name: "Stop sample test", exact: true }).click();
  await expect(page.getByRole("status").filter({ hasText: /^Stopped$/ })).toBeVisible();
  await page.reload();
  await expect(page.getByRole("status").filter({ hasText: /^Stopped$/ })).toBeVisible();
  const replayStopped = await (await request.post(`/api/projects/${projectId}/sample-operations`, { data: stopInput })).json();
  expect(replayStopped.status).toBe("cancelled");
  await page.screenshot({ path: "../docs/execution/guided-journey/sample-stopped.png", fullPage: true });
  await page.getByRole("button", { name: "Review scope for a new test", exact: true }).click();
  await expect(page.getByRole("region", { name: "Sample authorization" })).toBeVisible();
  // A lost outgoing POST keeps the same non-secret request key across refresh.
  await page.route(`**/api/projects/${projectId}/sample-operations`, (route) => route.abort("failed"), { times: 1 });
  await page.getByRole("checkbox", { name: "I reviewed the sample scope" }).check();
  const lostRequest = page.waitForEvent("requestfailed", (req) => req.method() === "POST" && req.url().endsWith("/sample-operations"));
  await page.getByRole("button", { name: "Test samples", exact: true }).click();
  await lostRequest;
  await expect(page).toHaveURL(/operation=/);
  const pendingId = new URL(page.url()).searchParams.get("operation");
  await page.reload();
  await page.getByRole("button", { name: "Retry this authorized request", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Does this result match what you need?" })).toBeVisible();
  expect(new URL(page.url()).searchParams.get("test")).toBe(pendingId);
});
