import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = new URL('../', import.meta.url);
const source = JSON.parse(readFileSync(new URL('design/annotagent-visual-system/tokens/tokens.json', root), 'utf8'));
const declarations = values => Object.entries(values).map(([key, value]) => {
  if (!/^[a-z0-9-]+$/.test(key) || typeof value !== 'string' || /[;{}\n]/.test(value)) throw new Error(`Invalid design token ${key}`);
  return `  --aa-${key}: ${value};`;
}).join('\n');
if (source.schema_version !== 2 || !source.common || !source.themes.light || !source.themes.dark) throw new Error('Unsupported token source');
const css = `/* Generated by scripts/generate-tokens.mjs from the canonical tokens.json. */
:root, [data-aa-theme="light"] {
  color-scheme: light;
${declarations(source.common)}
${declarations(source.themes.light)}
}

[data-aa-theme="dark"], .aa-dark {
  color-scheme: dark;
${declarations(source.themes.dark)}
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after { scroll-behavior: auto !important; transition-duration: 0.01ms !important; animation-duration: 0.01ms !important; animation-iteration-count: 1 !important; }
}
`;
for (const path of ['web/src/annotagent-tokens.css', 'design/annotagent-visual-system/tokens/tokens.css', 'design/annotagent-visual-system/web/src/styles/annotagent-tokens.css']) {
  const file = new URL(path, root);
  if (process.argv.includes('--check')) {
    if (readFileSync(file, 'utf8') !== css) throw new Error(`Stale generated tokens: ${fileURLToPath(file)}; run node scripts/generate-tokens.mjs`);
  } else writeFileSync(file, css);
}
